<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DocumentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */

    public function run()
    {
        $categories = [
            "Hutan Alam",
            "Hutan Alam",
            "Karhutla",
            "Deforestasi",
            "Hutan Alam",
            "Hutan Alam",
            "Karhutla",
            "Hutan Alam",
            "Sawit,Konsesi",
            "Hutan Alam, Konsesi",
            "Deforestasi",
            "Hutan Alam, Sawit, Karhutla",
            "Sawit",
            "Gambut",
            "Sawit",
            "Karhutla",
            "Sawit",
            "Deforestasi",
            "Deforestasi",
            "Hutan Alam",
            "Hutan Alam",
            "Konsesi",
            "Hutan Alam, Karhutla",
            "Hutan Alam",
            "Hutan Alam",
            "Karhutla",
            "Sawit",
            "Sawit",
            "Perhutanan Sosial",
            "Karhutla",
            "Karhutla",
            "Gambut",
            "Hutan Alam",
            "Konsesi",
            "Sawit",
            "Karhutla",
            "Hutan Alam",
            "Hutan Alam",
            "Hutan Alam",
            "Sawit",
            "Konsesi",
            "Perhutanan Sosial, Konsesi",
            "Hutan Alam",
            "Karhutla",
            "Deforestasi",
            "Karhutla",
            "Sawit",
            "Karhutla",
            "Sawit",
            "Karhutla",
            "Deforestasi",
            "Karhutla",
            "Karhutla",
            "Hutan Alam",
            "Deforestasi",
            "Gambut",
            "Sawit",
            "Deforestasi",
            "Karhutla",
            "Sawit",
            "Deforestasi",
            "Deforestasi",
            "Konsesi",
            "Sawit",
            "Sawit",
            "Gambut",
            "Masyarakat Adat",
            "Gambut",
            "Gambut",
            "Karhutla",
            "Sawit",
            "Gambut",
            "Gambut",
            "Sawit, Biofuel",
            "Perhutanan Sosial",
            "Sawit, Biofuel",
            "Deforestasi",
            "Hutan Alam",
            "Hutan Alam, Deforestasi",
            "Sawit",
            "sawit",
            "Karhutla",
            "Hutan Alam",
            "Hutan Alam",
            "Hutan Alam",
            "Hutan Alam",
            "Gambut",
            "Sawit",
            "Biofuel",
            "Sawit, Biofuel",
            "Perhutanan Sosial",
            "Konsesi",
            "Hutan Alam, Konsesi",
            "Deforestasi",
        ];

        $tags = [
            "Papua",
            "Papua Barat",
            "Hutan Alam dalam Konsesi, Hutan Alam Clean and Clear",
            null,
            "Kabupaten",
            "Provinsi",
            "Riau",
            "Hutan Alam dalam Konsesi",
            "Moratorium Sawit",
            "Hutan Alam dalam Konsesi",
            "Proyek Strategis Nasional",
            "Kabupaten",
            "PIPPIB",
            "Provinsi, PIPPIB",
            "PIPPIB, Hutan Alam dalam Konsesi",
            null,
            "Riau, Kalbar",
            null,
            null,
            null,
            null,
            "Tumpang Tindih",
            null,
            "Bencana, Provinsi",
            "Hutan Alam Clean and Clear",
            null,
            "Hutan Alam dalam Konsesi",
            "Izin Sawit, Tutupan Sawit",
            "PIAPS, Tumpang Tindih",
            null,
            null,
            null,
            null,
            "Proyek Strategis Nasional",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "Food Estate, Proyek Strategis Nasional",
            null,
            null,
            "Kalteng",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "Sulteng",
            "Sulteng",
            "Intact Forest Landscape",
            "Maluku",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "PBPH",
            null
        ];

        $filenames = [
            "Kondisi Hutan dan Lahan Papua 2019",
            "Kondisi Hutan dan Lahan Papua Barat 2019",
            "Update Fire Hotspot dan Hutan Oktober 2019",
            "Analisis Deforestasi 2006-2018",
            "Analisis Luas Hutan Alam Tiap Provinsi Kabupaten Kota",
            "Analisis Luas Hutan Alam Tiap Provinsi",
            "Analisis Karhutla PM 2,5 Riau_Rev4",
            "Analisis Hutan dan Lahan 2018",
            "Analisis Usulan Area Moratorium Sawit Auriga",
            "Analisis Hutan Alam dalam Konsesi 2018",
            "Analisis Indikasi Deforestasi pada Proyek Strategis Nasional",
            "Analisis Hutan Alam, Gambut, Area Terbakar, dan Izin serta Tutupan Sawit di tiap Kabupaten dan Kota",
            "Area Perkebunan Sawit, IUPHHK HT, IUPHHK HT dalam PIPPIB Revisi XV",
            "Kondisi Gambut 2019",
            "Ulasan Izin Sawit Riau Nov",
            "Ulasan Area Terbakar di Izin Sawit",
            "Analisis PBB Sawit Riau Kalbar",
            "Update Deforestasi 2018-2019",
            "Analisis Hutan dan Lahan Fokus RFN1",
            "Analisis Kondisi Eksisting Hutan dan Lahan (Bagian 2)",
            "Ulasan Tutupan Lahan 2019",
            "Silang_Sengkarut_Izin",
            "Ulasan Singkat Hutan dan Karhutla Webinar ASRI",
            "Hutan Alam Gambut Pilkada 2020 Bencana",
            "Ulasan Hutan Alam 2019",
            "Ulasan Area Potensi Terbakar Jan-Sep 2020",
            "Ulasan Izin dan Tutupan Sawit Sept",
            "Tipe dan Jenis Izin Sawit Kalbar Riau",
            "Analisis PIAPS Revisi 4",
            "Karhutla, Covid-19, dan Kaitannya dengan Hutan Indonesia",
            "Ulasan Area Terbakar di Izin Sawit",
            "Gambut Terkini",
            "Hutan Alam di dalam Fungsi Kawasan Hutan",
            "Indonesia Darurat Tenurial",
            "Izin Sawit di Kawasan Hutan Lindung dan Konservasi",
            "Kajian Karhutla",
            "Analisis Kondisi Eksisting Tutupan Lahan Kawasan Hutan 2018 CILAKA",
            "Luasan Area Penggunaan Lain 2015-2019 (Studi Kasus Riau & KalBar)",
            "Pendekatan Kondisi Hutan Alam 2019 dan Pilkada",
            "Sawit Terkini",
            "Silang Sengkarut Izin (2)",
            "Silang Sengkarut Izin (1)",
            "Simulasi Perubahan Hutan Alam DAS di 8 Kabupaten Papua Barat",
            "Ulasan Area Terbakar 2019",
            "Ulasan Data Deforestasi Indonesia dan Usulan Penambahan Area Moratorium",
            "Ulasan Kebakaran Lahan 2019",
            "Potret Izin dan Tutupan Sawit Indonesia (2)",
            "Hotspot Report Jan-Maret",
            "Analisis Kapasitas Pengembangan Izin Sawit Riau Kalbar",
            "Kajian Kebakaran Hutan dan Lahan 2019 dan ART",
            "Kajian Deforestasi 2003-2018",
            "Analisis Tingkat Kerawanan Ganda Karhutla Covid Wilayah LTKL",
            "Analisis Tingkat Kerawanan Ganda Karhutla Covid Muba",
            "Analisis Data SOFOR 2020",
            "Hutan Alam di Food Estate (3)",
            "Ulasan Data Gambut",
            "Ulasan Spasial Tahun Terbit Izin Sawit",
            "Kondisi Terkini 2 Taman Nasional Kalteng",
            "Area Potensi Terbakar 2020 dan 2021",
            "Sebaran Izin Sawit RSPO dan ISPO",
            "Ulasan Statistik Deforestasi 2019-2020 (1)",
            "Ulasan Deforestasi Hutan Alam 2019-2020",
            "Ulasan PIPPIB",
            "Palm Oil Spatial Update",
            "Ulasan Sawit Bersertifikat ISPO dan RSPO",
            "Ulasan Area Prioritas Restorasi Gambut BRG",
            "Ulasan Wilayah Adat",
            "Ulasan FEG Rekomendasi Target Restorasi BRGM",
            "Ulasan Izin Sawit di Fungsi Ekosistem Gambut",
            "Update APT Mei 2021 (3)",
            "Ulasan Izin Sawit di Papua (2)",
            "Peta PIR dan FEG Tanpa Tumpang Tindih",
            "Rekomendasi Target Restorasi_BRGM 2021-2024 (3)",
            "Quicklook Data PKS Biofuel",
            "Selidik_Spasial PIAPS (0)",
            "Analisis PKS Pemasok Biodiesel (2).pdf",
            "Update Spasial Deforestasi dan Hutan Alam di Usaha Sawit 2011-2020 (2)",
            "Update Hutan Alam Belum Terlindungi (2)",
            "Update Spasial Deforestasi dan Hutan Alam 2011-2020_Madani-2021",
            "Update Spasial Usaha Sawit di Kawasan Hutan (2) Sept 2021",
            "Update Spasial Tutupan Sawit di Kawasan Hutan (4)",
            "Update Area Potensi Terbakar 1 Jan-14 Agustus 2021",
            "Hutan Alam Belum Terlindungi Sulteng",
            "Fokus 40 Lokasi Hutan Alam Belum Terlindungi Sulteng",
            "Analisis Intact Forest",
            "Ulasan RTRW Maluku (1)",
            "Ulasan FEG Clean and Clear",
            "HPK Tidak Produktif untuk Pengembangan Usaha Sawit",
            "Ulasan Ketersediaan Lahan Feedstock Biofuel",
            "Optimalisasi Lahan di Usaha Sawit untuk BBN",
            "Potret Perhutanan Sosial 2022",
            "Ulasan Spasial Pencabutan Izin 2022",
            "Sari Informasi Hutan dan Lahan 2022",
            "Untaian Makna Data Deforestasi 2003-3020"
        ];

        $filesources = [
            "Madani",   "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani"
        ];

        $years = [
            2019, 2019, 2019, 2019, 2019, 2019,
            2019,           2019,
            2019,            2019,
            2019,            2019,
            2019,            2019,
            2020,            2020,
            2020,            2020,
            2020,            2020,
            2020,            2020,
            2020,            2020,
            2020,            2020,
            2020,            2020,
            2020,            2020,
            2020,            2020,
            2020,            2019,
            2020,            2020,
            2020,            2020,
            2020,            2020,
            2020,            2020,
            2020,            2020,
            2020,            2020,
            2020,            2020,
            2020,            2020,
            2020,            2020,
            2020,            2021,
            2021,            2021,
            2021,            2021,
            2021,            2021,
            2021,            2021,
            2021,            2021,
            2021,            2021,
            2021,            2021,
            2021,            2021,            2021,
            2021,
            2021,
            2021,
            2021,
            2021,
            2021,
            2021,
            2021,
            2021,
            2021,
            2021,
            2021,
            2021,
            2021,
            2021,
            2021,
            2021,
            2021,
            2021,
            2022,
            2022,
            2022,
            2022
        ];

        $links = [
            "https://drive.google.com/drive/folders/1Umlx_xoMGVaoixxSab6UoReSic-Ksoq1?usp=sharing",
            "https://drive.google.com/file/d/1fDSP3PusLQk0VQKgUeZ8lC_nIrF_1YPn/view?usp=sharing",
            "https://drive.google.com/file/d/160Rrn2vPNdUocQMqTrxTutURMmM-oLMq/view?usp=sharing",
            "https://drive.google.com/file/d/1ISkR-Enaw7_v5aomV7gBKgfDnjiXMEgc/view?usp=sharing",
            "https://drive.google.com/file/d/1rJpQZ3Z6Irx-dzjw2LquSUTWjAzOMy5X/view?usp=sharing",
            "https://drive.google.com/file/d/1TOVPa6E6MTk1n4lfrz5eVoJdyTk6OVq3/view?usp=sharing",
            "https://drive.google.com/file/d/1c6rxCF6c3tN9DxvxziBym4bmITE176qH/view?usp=sharing",
            "https://drive.google.com/file/d/1_tzeaLIzQk4ZiwuoEeVmzvvH7JWDmGlx/view?usp=sharing",
            "https://drive.google.com/file/d/1pkeZNfk8Ri_74vxQHLiKK4SZmwqZlBuj/view?usp=sharing",
            "https://drive.google.com/file/d/1L5q13WRiRbGRJ0sTDX_75bo1woheruXq/view?usp=sharing",
            "https://drive.google.com/file/d/1uw47vbKmAOBohn9HvMw215_G7Ub8vX6h/view?usp=sharing",
            "https://drive.google.com/file/d/1pfhV-zm0lGPqKSCfOWiz9csfAdLLUdvg/view?usp=sharing",
            "https://drive.google.com/file/d/1OhCZsdzxfqkat79FQaGKeb-R8VKJeQal/view?usp=sharing",
            "https://drive.google.com/file/d/1EDnB1_MQQzWDQ1nV6nIKqkEud0g4m02X/view?usp=sharing",
            "https://drive.google.com/file/d/14PV156-K76kRy1F0J6VkEZoLracLK2K_/view?usp=sharing",
            "https://drive.google.com/file/d/1QCifmstGUngc2LJNX9T7K4Wy78MIk3Rw/view?usp=sharing",
            "https://drive.google.com/file/d/1AQifhAAjZDUfZKZuxpGuqXSOASBFvntM/view?usp=sharing",
            "https://drive.google.com/file/d/1M4xaCZCm3NtqsUruNlxfICba1Hq7V_cW/view?usp=sharing",
            "https://drive.google.com/file/d/1Rgr3l4pLzVCdzUOWgKxCkgfcjmTpXa7b/view?usp=sharing",
            "https://drive.google.com/file/d/1NBupevM-uoEcgUDK-41zcaRn8rAiJuSl/view?usp=sharing",
            "https://drive.google.com/file/d/1MOjbEUW_0TCcNM80rbpwuVn4yPqrOobT/view?usp=sharing",
            "https://drive.google.com/file/d/1RPTelxz8Q8MTk6aYzFpcGutqyIJapDzC/view?usp=sharing",
            "https://drive.google.com/file/d/1vw4dQUUl7m_v1ICk1kJcGfvS1Iez-ATM/view?usp=sharing",
            "https://drive.google.com/file/d/1MPuXkuOCtagPI1HwGRTSQiEXNksPkXpF/view?usp=sharing",
            "https://drive.google.com/file/d/1l3QiIMQXSpLHvCaEMlaEy5k3T0rZtEYH/view?usp=sharing",
            "https://drive.google.com/file/d/1botAtj_67dS1xd9GhGXhb57WubU-mNnj/view?usp=sharing",
            "https://drive.google.com/file/d/12FchUwhicxPG0hNWvalcJzJyxi3dg5ow/view?usp=sharing",
            "https://drive.google.com/file/d/1Uu8AbLYcWdrclHsogwNKFTX5oS1hDR1o/view?usp=sharing",
            "https://drive.google.com/file/d/1nN-QOIujIjSDSaNidttsXvvvyorG6wlT/view?usp=sharing",
            "https://drive.google.com/file/d/1dm5YoG_MnpIqis3FEefp0OMYKBNzgThr/view?usp=sharing",
            "https://drive.google.com/file/d/1QCifmstGUngc2LJNX9T7K4Wy78MIk3Rw/view?usp=sharing",
            "https://drive.google.com/file/d/1C53T30V9usGphQs6h1SF6RYZ2DTFGV3f/view?usp=sharing",
            "https://drive.google.com/file/d/1Uvk66GHUQgPHMYGh-yh7kUzRnnoui9ej/view?usp=sharing",
            "https://drive.google.com/file/d/151OMSMMvwhPuG1YfhnP5dBLc7qzqKibk/view?usp=sharing",
            "https://drive.google.com/file/d/1QGqVaxDFRp_RAbWBk4ztyvAe-vuTiX1m/view?usp=sharing",
            "https://drive.google.com/file/d/11U0xfkU8MP5kabvnGiLZEl4VNnlJwDZ_/view?usp=sharing",
            "https://drive.google.com/file/d/1zYXd1nx3bhPhbEvrQQYzAdRBt52_dPvn/view?usp=sharing",
            "https://drive.google.com/file/d/17cEmc49dPQB9nw9Fkt2ZgDqWyfWE9s75/view?usp=sharing",
            "https://drive.google.com/file/d/1SOYB6stozCZOJjeKVXe6PwMz4X2fMYE6/view?usp=sharing",
            "https://drive.google.com/file/d/1NvgdsmRzPdxFUuq5dxDe-Vc4fNWHBrYn/view?usp=sharing",
            "https://drive.google.com/file/d/1VI-uUFW5fKj0L9U4GMKxWZicCP3vZq-d/view?usp=sharing",
            "https://drive.google.com/file/d/17XIrQ7eBYLwqXEHWKPafy7g0iife5PmB/view?usp=sharing",
            "https://drive.google.com/file/d/1nWIxF4f5q5iH8s3AphEVnfbshApIpapB/view?usp=sharing",
            "https://drive.google.com/file/d/12HSOvw2r_z2_qE978oz23QJp9sW5q-Ha/view?usp=sharing",
            "https://drive.google.com/file/d/18l69w89WfboktSzbF_51eDvOUY7VUdZ8/view?usp=sharing",
            "https://drive.google.com/file/d/1mV1gO8McNYXqOCXjDQB_89zQyqhEiqCL/view?usp=sharing",
            "https://drive.google.com/file/d/1DHExh-LLVRgdL40Jl7l4gxojv0ltYRdB/view?usp=sharing",
            "https://drive.google.com/file/d/1ldQOW2X76KIFAlO7yoMKXt8WdLYi3l-S/view?usp=sharing",
            "https://drive.google.com/file/d/1wmPVnbIi48sWOzds6V-ZUYfz24wLLqG9/view?usp=sharing",
            "https://drive.google.com/file/d/1si_qNHdIb3Q7gc6_clvde568tImWRXd7/view?usp=sharing",
            "https://drive.google.com/file/d/1wo1BzGWYRdgXPVkdXOnlgGahzlve0uHe/view?usp=sharing",
            "https://drive.google.com/file/d/12AgzPIPr11PICEGoh4wWnBYs4hXVR0d4/view?usp=sharing",
            "https://drive.google.com/file/d/1qBp7joJdECL_cIVT06wsSnEUPVnLuYsw/view?usp=sharing",
            "https://drive.google.com/file/d/1retoowA8vI7fIxSrnyJgdtthO68AxNew/view?usp=sharing",
            "https://drive.google.com/file/d/12YkBTSsNGIsgTaHpBA_bYNvVQ2-wuwaz/view?usp=sharing",
            "https://drive.google.com/file/d/1NbIxYdZrFM4MmzJwQfvHF5o8-AutX_Xz/view?usp=sharing",
            "https://drive.google.com/file/d/1BW2S1LdB7IijF5aLZ6U0j6BZqix9sZc6/view?usp=sharing",
            "https://drive.google.com/file/d/1n4AeTZJOYyeq9zOQS8n7Xfni08Z4R9Yt/view?usp=sharing",
            "https://drive.google.com/file/d/1Etbe9Uc6WdBEV0e8x2PiSA-JQUuSgr80/view?usp=sharing",
            "https://drive.google.com/file/d/1rOehHbMNtHCNJrCraMXVo78h8KPj25TL/view?usp=sharing",
            "https://drive.google.com/file/d/1y2E4WjhTO8DrY58XYzMCk5xXCsHV1YUh/view?usp=sharing",
            "https://drive.google.com/file/d/1BFK1_jHua81E3vRO5L49thsBy9ylZWbV/view?usp=sharing",
            "https://drive.google.com/file/d/1hFkBAwtx6l1as9Yjp5gnzLstCk_ZdLP8/view?usp=sharing",
            "https://drive.google.com/file/d/17FhtKxVYD-yhdp9wkBcKCLb3m1uUEasD/view?usp=sharing",
            "https://drive.google.com/file/d/1AnfITPGujfFbIC9_5L_QZ57JiZCCumRh/view?usp=sharing",
            "https://drive.google.com/file/d/1PGJHWjKSwohMgBp0U2W6nGI6Pg7xRnAl/view?usp=sharing",
            "https://drive.google.com/file/d/1fXP2ppM9VfNYUKRRPdxw16piRGwMCekh/view?usp=sharing",
            "https://drive.google.com/file/d/1bUlR2p8Fr2VpmWCbM2kql-0D5M1KOQ6E/view?usp=sharing",
            "https://drive.google.com/file/d/1Kcrq_LOb8SF4pvwajf9FXq47E09lfZRA/view?usp=sharing",
            "https://drive.google.com/file/d/1oGC_0dy_deSpS6XxDis3gFTWmbGSoFjX/view?usp=sharing",
            "https://drive.google.com/file/d/1vUnbVcDnU0I4axD9qNKp-8PoY5P-GF9Y/view?usp=sharing",
            "https://drive.google.com/file/d/1IPdSrBL37Jj3lzKxPG61BiMfgCd7X1Bn/view?usp=sharing",
            "https://drive.google.com/file/d/18SrjkBg7v4QzZkPUM280ptrtTfZuklDY/view?usp=sharing",
            "https://drive.google.com/file/d/1cpbYKa300oovXsB2-myCf5yV_JbfqeDo/view?usp=sharing",
            "https://drive.google.com/file/d/1G1Y-VNsXraOc97zMoNU7vrMHOFodyTPp/view?usp=sharing",
            "https://drive.google.com/file/d/1DoCBWf7lSS1Ea3s6ubPk4_9-6LVo6Xpq/view?usp=sharing",
            "https://drive.google.com/file/d/1NIOdovmeUHV23K947ZPIjl59US7Vlrtd/view?usp=sharing",
            "https://drive.google.com/file/d/1cJhTJtj3LQvMqUmPb8NQpLUEDuQpY-TD/view?usp=sharing",
            "https://drive.google.com/file/d/1of37Jvgu3FCumQcstlE2HD8EjBlHo0GJ/view?usp=sharing",
            "https://drive.google.com/file/d/11HkPTNI54JxbePPNUwNQO1yD2Msz6AcM/view?usp=sharing",
            "https://drive.google.com/file/d/1TDB1EzpHUIORQGYh2IW1Zn-eeMuEOCPS/view?usp=sharing",
            "https://drive.google.com/file/d/1mOSl8BzlRTstjiQ4C9sgtoVPDbRJHXCQ/view?usp=sharing",
            "https://drive.google.com/file/d/12O9XRhemLzPoegAaijZMtNkqUzaByAI_/view?usp=sharing",
            "https://drive.google.com/file/d/17dEbA9f5AxgSmBUkDmPRCTcRd-FbBLao/view?usp=sharing",
            "https://drive.google.com/file/d/1wJ6YcK-OJ5Ng3z3Ygb0AhrHTnP73jzGv/view?usp=sharing",
            "https://drive.google.com/file/d/1UUrD4cVN3x9-yG3VMw8bPn4ZNlsgzkM3/view?usp=sharing",
            "https://drive.google.com/file/d/1TNn3zzpHztw0wv814bHytOXcFoo5QJg1/view?usp=sharing",
            "https://drive.google.com/file/d/1C6C6rmJInxjSHFqk_cbr89CBYc-o09ua/view?usp=sharing",
            "https://drive.google.com/file/d/1t8oBDOSFkhq89ErfinjO30vmM6YRvNMa/view?usp=sharing",
            "https://drive.google.com/file/d/1RToLnuNFHbfkagFUMozB6_rzU3JIa78v/view?usp=sharing",
            "https://drive.google.com/file/d/1zbI7s_bcc6PAa67GSWaaWoW3OL3KYVty/view?usp=sharing",
            "https://drive.google.com/file/d/1jXzOkOgS_g8e22LjC4PpGcnQJkVgTvz8/view?usp=sharing",
            "https://drive.google.com/file/d/19_DNBcRvgLnJ5j9SkzNa4q7ITkNSWQdX/view?usp=sharing",
            "https://drive.google.com/file/d/1JQJBzpga-jxcAf3tfGNFGaAOUcpK8-GT/view?usp=sharing",
            "https://drive.google.com/file/d/1cC4Gd61tmYQhriITxFq_nbcQTEmdHGn7/view?usp=sharing",

        ];

        $desc = [
            "Kawasan Hutan dan Tutupan Hutan Papua\nPeta Konsesi di Papua\nPeta Area Silang Sengkarut Konsesi Papua\nPeta Hutan Alam dalam Konsesi Papua\nPeta Hutan Alam di Luar Konsesi Papua\nPeta Hutan Alam Berpotensi Dilindungi Papua",
            "Kawasan Hutan dan Tutupan Hutan Papua Barat\nPeta Konsesi di Papua Barat\nPeta Area Silang Sengkarut Konsesi Papua Barat\nPeta Hutan Alam dalam Konsesi Papua Barat\nPeta Hutan Alam di Luar Konsesi Papua Barat\nPeta Hutan Alam Berpotensi Dilindungi Papua Barat\nSkenario Pemenuhan Target 70% Kawasan Lindung",
            "Fire hotspots Januari-Oktober 2019\nHutan alam dalam konsesi\nHutan alam sekunder yang belum dibebani konsesi",
            "Peta Area Deforestasi 2006-2018 di Konsesi (HT, HA, Minerba, Sawit)",
            "Persentase Hutan Alam di Provinsi\nLuas Hutan Alam di Setiap Provinsi",
            "Luas Hutan Alam Indonesia 2018\nSebaran Konsesi, PIPPIB, PIAPS\nHutan Alam Tersisa di Luar Konsesi 9,5 Juta Ha\nPersentase Ketersediaan Hutan Alam Tiap Provinsi Tutupan Lahan 2018\nPersentase Hutan Alam di Luar Konsesi Tiap Provinsi 2018\nLuas Hutan Alam Tiap Provinsi 2018\nLuas Hutan Alam Tanpa Beban Izin Tiap Provinsi",
            "Titik Api Januari-Juli 2019 di Riau dan Pemodelan PM 2,5",
            "Luas Kawasan Hutan dan Hutan 2018",
            "Luas Usulan Area Moratorium Sawit Auriga\nLuas Area IUPHHK HT, HA, dan Izin Sawit Eksisting di Area Usulan Moratorium Sawit Auriga",
            "Luas Hutan Alam dalam Konsesi 2018 IUPHHK HT IUPHHK HA Izin Sawit",
            "Indikasi area terdeforestasi (seluruh Indonesia) dari proyek strategis nasional",
            "Peta Sebaran Hutan Alam, Izin Sawit, Tutupan Sawit, Gambut, Area Terbakar 2015-2018\nSebaran Hutan Alam di APL\nHutan Alam di APL Tingkat Kabupaten\nSebaran Gambut Tingkat Kabupaten Kota\nSebaran Area Terbakar Tingkat Kabupaten Kota 2015-2018\nSebaran Izin dan Tutupan Sawit Tingkat Kabupaten Kota\nSebaran Izin dan Tutupan Sawit di Gambut Tingkat Kabupaten Kota",
            "Area perkebunan sawit di PIPPIB Revisi XV\nArea IUPHHK HT di PIPPIB Revisi XV\nArea IUPHHK HA di PIPPIB Revisi XV",
            "Area prioritas restorasi gambut di 7 provinsi\nSebaran fire hotspot (FHS) 1 Januari-19 Oktober 2019\nPIPPIB, area perkebunan sawit, dan IUPHHK-HT dalam area prioritas restorasi gambut",
            "Sebaran Konsesi di Provinsi Riau\nSengkarut PIPPIB dan PIAPS dengan Konsesi\nSengkarut Izin Sawit dengan Konsesi Lain\nSebaran Tutupan dan Izin Sawit Tingkat Kabupaten\nKaitan Data Tutupan dan Izin Sawit Terdata\nSebaran Hutan Alam 2019 di Riau\nSebaran Hutan Alam 2019 di Izin Sawit Terdata di Riau",
            "Kaitan dengan Permen ATR BPN No 15 Tahun 2016",
            "Izin dan Tutupan Sawit Riau Mei 2020 Berdasarkan Tipe dan Jenis Usaha\nDetil Tutupan Sawit Kalbar\nIzin Sawit di Riau dan Kalbar Mei 2020 Tingkat Kabupaten\nArea Fokus Pendetilan Izin Sawit Riau dan Kalbar",
            "Perubahan Tutupan Lahan 2018-2019 di Area Deforestasi 2018-2019",
            "Hutan Alam, Konsesi, PIPPIB, PIAPS di Kalimantan Utara, Maluku Utara, Maluku, Papua, Papua Barat",
            "Hutan alam di luar konsesi: Kalimantan Utara, Maluku, Maluku Utara, Papua, dan Papua Barat Zoom Kabupaten",
            "Tutupan Lahan 2019 Indonesia\nTutupan Lahan 2019 Tingkat Provinsi",
            "Data izin dan wilayah yang telah diinventarisasi tahun 2020\nSebaran area silang sengkarut PIPPIB 2020 dan Izin Lainnya\nSebaran area silang sengkarut PIAPS revisi 04 dan Izin lainnya\nSebaran area silang sengkarut izin sawit dan Izin Lainnya\nPendetilan Sengkarut Izin Sawit Berdasarkan Tipe Usaha\nSilang Sengkarut 3 Konsesi Sekaligus",
            "Hutan Alam 2019\nHutan Alam di Luar Konsesi dan Belum Terlindungi 2019\nAkumulasi Jejak Terbakar 2015-2019 per Provinsi\nPersentase Hutan Alam per Provinsi 2019\nProyeksi Provinsi yang Akan Kehilangan Hutan Alam Hingga 2048\nPerkembangan Area Potensi Terbakar Agustus 2020\nHutan Alam dalam Pilkada 2020",
            "Analisis hutan alam dan kejadian bencana di provinsi peserta pilkada 2020",
            "Sebaran Perubahan Hutan Alam 2018-2019 per Provinsi\nHutan Alam 2019 dan Fungsi Kawasan\nSebaran Perubahan Hutan Alam di Luar Konsesi 2018-2019 di Tiap Provinsi\nHutan Alam Tidak Terlindungi Moratorum di Luar Konsesi 2019\nHutan Alam Tidak Terlindungi Moratorum di Luar Konsesi 2019 Berdasarkan Fungsi Kawasan",
            "Validasi Data Hotspot\nPerkembangan Area Potensi Terbakar\nJanuari-September 2020",
            "Ulasan terbaru data izin sawit hingga Juni 2020\nUlasan terbaru tutupan sawit 2019\nKeterkaitan kedua data tersebut\nHutan alam tersisa di izin sawit",
            "Sebaran Jenis Izin Sawit di Kalbar & Riau\nSebaran Tipe Izin Sawit di Kalbar & Riau",
            "Sebaran Komponen PIAPS Revisi 4\nSebaran PIAPS Revisi 4 per Provinsi\nSebaran Fungsi Kawasan Hutan pada PIAPS Revisi 4\nSebaran Tutupan Lahan pada PIAPS Revisi 4\nSebaran Izin dan Tutupan Sawit di PIAPS Revisi 4\nKomposisi Jenis Izin Sawit di PIAPS Revisi 4\n20 Perusahaan dengan Luas Izin Sawit Terluas di PIAPS Revisi 4",
            "Kaitan kasus positif Covid-19 dengan hutan alam serta gambut\nKaitan kasus positif Covid-19 dan karhutla\nKaitan kasus positif Covid-19 dan perkembangan hotspot modis\nPenentuan indeks ancaman ganda rawan karhutla dan waspada Covid-19",
            "Ulasan terbakar 2019\nUlasan terbakar 2019 di kawasan izin sawit\nAnalisis statistic luasan terbakar 2019 di kawasan izin sawit",
            "Sebaran Fungsi Ekosistem Gambut\nSebaran IUPHHK HT dalam Fungsi Ekosistem Gambut\nSebaran Izin Sawit dalam Fungsi Ekosistem Gambut\nSebaran Area Terbakar 2015-2019 dalam Fungsi Ekosistem Gambut",
            "Luasan hutan alam dalam fungsi kawasan hutan\nAnalisis statistik hutan alam dalam fungsi Kawasan\nHutan alam di setiap fungsi kawasannya\nTabular data hutan alam dalam fungsi kawasan",
            "Hutan Alam Indonesia Tahun 2018\nTumpang Tindih Peruntukan Lahan\nHutan Alam Belum Terbebani Izin\nProyek Strategis Nasional\nProyek Strategis Nasional di Hutan Alam",
            "Izin sawit di kawasan hutan lindung dan konservasi 2015, 2017, dan 2019",
            "Ulasan Kebakaran 2019\nKarakteristik Area Rawan Terbakar (ART) 2020\nPeta ART vs Hotspot Januari-Maret 2020\nUpdate Hotspot 2020 (17 April 2020)",
            "Persentase Hutan Alam dan Kawasan Hutan 2018\nKarhutla 2014-2019 dan Deforestasi 2006-2018 di Seluruh Wilayah\nKondisi Eksisting, Hutan Alam Beserta Laju Karhutla dan Deforestasi\nKondisi Eksisting, Hutan Alam Primer Beserta Laju Karhutla dan Deforestasi\nKondisi Eksisting, PIPPIB 2019 Beserta Laju Karhutla dan Deforestasi\nSimulasi I Gambaran 20 hingga 40 tahun ke depan untuk Kawasan Hutan dan Hutan Alam Jika Omnibus Law Diterapkan\nSimulasi II Gambaran 20 hingga 40 tahun ke depan untuk Izin Sawit Jika Omnibus Law Diterapkan",
            "Analisis Statistik APL 2015-2019 Kalbar\nAnalisis Statistik APL 2015-2019 Riau\nSebaran Tutupan Lahan pada APL 2015-2019 Kalbar\nSebaran Tutupan Lahan pada APL 2015-2019 Riau",
            "Hutan Alam 2019, Deforestasi Bruto 2003-2018, Akumulasi Jejak Terbakar 2015-2019 di Provinsi Peserta Pilkada 2020\nPola Penerbitan Izin Lokasi dan IUP Sawit di Sekitar Tahun Pilkada\nAnalisis yang Sama di 10 Kabupaten Peserta Pilkada dengan Hutan Alam Terluas",
            "Kondisi Izin Sawit Terkini\nKondisi Tutupan Sawit Terkini",
            "Sebaran area silang sengkarut PIPPIB 2020 periode 01 terhadap beberapa izin lainnya\nSebaran area silang sengkarut PIAPS Revisi 04 terhadap beberapa izin lainnya\nSebaran area silang sengkarut izin sawit terhadap beberapa izin lainnya\nPendetailan sebaran area silang sengkarut izin sawit terhadap beberapa izin lainnya\nPendetailan sebaran area silang sengkarut dengan 3 konsensi dan izin sekaligus",
            "Sebaran area silang sengkarut PIPPIB 2020\nSebaran area silang sengkarut PIAPS Revisi 4\nSebaran area silang sengkarut Izin Sawit",
            "45 DAS terluas di 8 kabupaten kota kajian\nHutan alam yang tidak terlindungi PIPPIB\nSimulasi perubahan hutan alam yang tidak terlindungi PIPPIB",
            "Ulasan area terbakar 2019 tiap provinsi\nArea terbakar 2019 berdasarkan PIPPIB 2019\nArea terbakar 2019 berdasarkan data konsesi",
            "Ulasan Data Deforestasi Indonesia\nUsulan Penambahan Area Moratorium\nLampiran Peta",
            "Sebaran Area Terbakar 2019\nLuas Area Terbakar 2015-2019\nSebaran Area Terbakar 2019 per Provinsi dan Kabupaten Kota\nSebaran Area Terbakar 2019 per Tutupan Lahan\nArea Terbakar 2019 di dalam PIPPIB dan PIAPS\nArea Terbakar 2019 di dalam Izin Sawit, IUPHHK HT, IUPHHK HA, Gambut dan Non Gambut\nStudi Kasus Kabupaten Hulu Selatan, Kalimantan Selatan",
            "Sekilas Data Izin Sawit Terdata\nSekilas Data Area Tutupan Sawit\nSebaran Area Tutupan dan Izin Sawit\nKomposisi Izin Sawit Terdata Berdasarkan Tipe dan Jenis Izin\nIzin Sawit x Tutupan Sawit\nSebaran Tutupan Lahan pada Izin Sawit Belum Tutupan Sawit\nSebaran Area Izin dan Tutupan Sawit Tumpang Tindih IUPHHK HT, HA, Migas, Minerba, PIAPS, PIPPIB, Ekosistem Gambut, Hutan Alam, Kawasan Hutan,",
            "Hotspot Januari-Maret 2020 dan Area Potensi Terbakar",
            "Tutupan Lahan APL Riau dan Kalbar 2019\nPelepasan Kawasan Hutan untuk Izin Sawit di Riau dan Kalbar 1987-2019\nAnalisis Kapasitas Pengembangan Izin Sawit di Riau dan Kalbar",
            "Ulasan Terbakar 2019\nArea Terbakar 2019 per Provinsi\nArea Terbakar 2019 per Tutupan Lahan\nArea Terbakar 2019 di Semak\/Belukar Rawa\nx Izin Konsesi dan Fungsi Ekosistem Gambut\nArea Terbakar 2019 di Hutan Produksi, KSA, KPA, dan Taman Buru x Izin Konsesi dan Fungsi Ekosistem Gambut\nArea Terbakar 2019 x PIPPIB 2019\nArea Terbakar 2019 di PIPPIB x Tutupan Lahan, Fungsi Ekosistem Gambut, dan Kedekatan dengan Konsesi\nPIAPS Revisi 4 x Konsesi dan Komposisi Area Terbakar dalam PIAPS\nArea Terbakar 2019 per Izin dan Konsesi\nArea Terbakar 2019 x Jejak Terbakar 2015-2019\nKomposisi Tutupan Lahan di Area Baru Terbakar 2019\nArea Baru Terbakar 2019 x Data Izin dan Konsesi x Data Pelepasan Kawasan Hutan\nPenentuan Model Area Rawan Terbakar 2020",
            "Deforestasi Bruto 2003-2018\nSebaran Area Deforestasi Bruto Berulang\nDeforestasi Bruto 2003-2018 per Provinsi (Akumulasi)\nDeforestasi Bruto 2003-2018 di 5 Konsesi\nKorelasi Deforestasi Bruto 2003-2018 Berulang di Area Konsesi",
            "Penentuan Area Rawan Terbakar 2020\nSebaran Area Rawan Terbakar 2020\nEstimasi Area Potensi Terbakar Januari-22 Mei 2020\nPenentuan ART dan APT di 12 Anggota LTKL\nPenentuan Peta Rawan Karhutla Covid di Wilayah LTKL\nTingkat Rawan Karhutla Covid di Wilayah LTKL di Kecamatan",
            "Pengantar\nSebaran Jejak Terbakar 2015-2019 di Kabupaten Musi Banyuasin\nSebaran Area Rawan Terbakar (ART) 2020 dan Area Potensi Terbakar (APT) 2020 di Kabupaten Musi Banyuasin\nSebaran Kerawanan Kebakaran dan Covid19 di Kabupaten Musi Banyuasin",
            "Tutupan Hutan SOFOR 2020 x Perhitungan Hutan Madani\nData Deforestasi SOFOR 2020 x Perhitungan Madani\nPerbandingan Data SOFOR 2020 dengan Rilis KLHK Maret 2021",
            "Keistimewaan Regulasi Food Estate\nSafeguards\nArea of Interest Food Estate di Kawasan Hutan, Ekosistem Gambut, dan Hutan Alam\nPotensi Nilai Kayu di Area of Interest Food Estate",
            "Luas Fungsi Ekosistem Gambut, Lahan Gambut, Prioritas Restorasi Gambut, Peta Restorasi Gambut\nStatus Kerusakan Ekosistem Gambut\nLuas Area Prioritas Restorasi Gambut 2016-2020\nTarget Restorasi 2016-2020\nEkosistem Gambut Terbakar 2019\nEkosistem Gambut, Prioritas Restorasi, Target Restorasi, dan Area Gambut Terbakar di 5 Izin Konsesi, PIPPIB, PIAPS, dan Wilayah Adat\nTrend Kebakaran Hutan dan Lahan di Ekosistem Gambut di Izin dan Konsesi, PIPIB, PIAPS, dan Wilayah Adat 2016-2019\nStatus Kerusakan x Prioritas dan Target Restorasi di 5 Izin dan Konsesi, PIPPIB, PIAPS, Wilayah Adat",
            "Izin Sawit Terdata Berdasarkan Jenis Izin dan Tipe Usaha 22,7 Juta Ha\n3,5 Juta Ha Hutan Alam di Izin Sawit\nHutan Alam di HGU Sawit\nEkosistem Gambut di HGU Sawit\nEkosistem Gambut Berhutan Alam di HGU Sawit\nHutan Alam di IUP Sawit\nEkosistem Gambut di IUP Sawit\nEkosistem Gambut Berhutan Alam di IUP Sawit\nData Izin Sawit yang Belum Terdata No SK-nya",
            "Izin Sawit di Sekitar Taman Nasional Tanjung Puting\nDeforestasi di dalam dan Sekitar Taman Nasional Tanjung Puting\nJejak Terbakar di dalam dan Sekitar Taman Nasional Tanjung Puting\nIzin Sawit di Sekitar Taman Nasional Sebangau\nDeforestasi di dalam dan Sekitar Taman Nasional Sebangau\nJejak Terbakar di dalam dan Sekitar Taman Nasional Sebangau",
            "Ulasan SIPONGI x APT 2020\nSebaran Luas Terbakar SIPONGI 2020\nSebaran APT vs SIPONGI 2020\nUji Area APT dengan SIPONGI 2020\nSebaran APT 2020\nSebaran APT 2020 di Izin dan Konsesi, PIPPIB 2020, PIAPS Revisi 4, dan Fungsi Ekosistem Gambut\nAPT di IZin dan Konsesi, PIPPIB, PIAPS, Wilayah Adat - Detil Eksositem Gambut\nAPT 2020 di Fungsi Ekosistem Gambut \nKomposisi APT 2020 di PIPPIB\nUlasan Data APT 2021 Update Maret 2021\nSebaran APT 2021 Januari-Februari 2021\nSebaran Izin Sawit 2020 dan APT 2020 dan Update APT Maret 2021",
            "Sebaran Jumlah Sertfikasi ISPO 2019 Kabupaten Kota\nSebaran Jumlah Sertfikasi RSPO 2019 Kabupaten Kota\nSebaran Jumlah Sertfikasi RSPO dan ISPO 2019 Kabupaten Kota\nSebaran Izin Sawit Terdata 2020 Detil Sertifikasi RSPO dan ISPO 2019",
            "Ulasan Data Tutupan Hutan versi SOFOR 2020 dan Rilis KLHK Maret 2021\nUlasan Data Deforestasi Bruto 2018-2019 ke 2019-2020",
            "Trend Deforestasi Hutan Alam 2011-2020\nDetil Deforestasi Hutan Alam 2019-2020 10 Kabupaten Tertinggi\nDeforestasi Hutan Alam 2019-2020 per Provinsi\nDeforestasi Hutan Alam 2019-2020 x Fungsi Kawasan Hutan\nDeforestasi Hutan Alam 2019-2020 di Izin dan Konsesi, PIPPIB, PIAPS, Wiayah Adat\nDeforestasi Hutan Alam 2019-2020 di Fungsi Ekosistem Gambut\nDeforestasi Hutan Alam 2019-2020 di Izin Sawit",
            "Data Izin dan wilayah yang telah diinventarisasi tahun 2020\nSebaran area silang sengkarut PIPPIB 2020 dan Izin Lainnya\nSebaran area silang sengkarut PIPPIB 2021 Revisi 1 Kalbar\nPengecualian",
            "Palm Oil Permit Data 27 Million Ha\n5 million ha of natural forests inside palm oil permits\n7 million ha of palm oil permits inside the forest zone\nPalm oil permits based on type of business\n14 million ha of palm oil permits unrecorded \n78% permits not registered for certification\n19.6 million ha palm oil cover\n16 million ha of palm oil permits not yet planted",
            "Sebaran Izin Sawit Sertifikasi ISPO dan RSPO\nSebaran Izin Sawit Sertifikasi ISPO dan RSPO per Provinsi\nSebaran Izin Sawit Sertifikasi ISPO dan RSPO x Kawasan Hutan\nSebaran Izin Sawit Sertifikasi ISPO dan RSPO x Tutupan Hutan Alam\nSebaran Izin Sawit Sertifikasi ISPO dan RSPO x Tutupan Sawit\nSebaran Izin Sawit Sertifikasi ISPO dan RSPO x Tipe Usaha\nSebaran Izin Sawit Sertifikasi ISPO dan RSPO x Jenis Izin\nSebaran Izin Sawit Sertifikasi ISPO dan RSPO x Area Terbakar 2019\nSebaran Izin Sawit Sertifikasi ISPO dan RSPO x Deforestasi Bruto 2019-2020",
            "Peta Indikatif Restorasi (PIR) BRG 2016-2020\nPeta Indikatif Restorasi (PIR) BRG 2016-2020 Provinsi\nPeta Indikatif Restorasi (PIR) BRG 2016-2020 - Data Prioritas\nPeta Indikatif Restorasi (PIR) BRG 2016-2020 x Kawasan Hutan\nPeta Indikatif Restorasi (PIR) BRG 2016-2020 x Tutupan Hutan Alam\nPeta Indikatif Restorasi (PIR) BRG 2016-2020 x Fungsi Ekosistem Gambut\nPeta Indikatif Restorasi (PIR) BRG 2016-2020 x Status Kerusakan Ekosistem Gambut\nPeta Indikatif Restorasi (PIR) BRG 2016-2020 x Izin dan Konsesi\nPeta Indikatif Restorasi (PIR) BRG 2016-2020 x Izin dan Konsesi, PIPPIB PIAPS\nPeta Indikatif Restorasi (PIR) BRG 2016-2020 x Jejak Terbakar 2015-2020\nPeta Indikatif Restorasi (PIR) BRG 2016-2020 - Detil Area Tidak Tumpang Tindih\nPeta Indikatif Restorasi (PIR) BRG 2016-2020 Tanpa Tumpang Tindih Provinsi\nPeta Indikatif Restorasi (PIR) BRG 2016-2020 Tanpa Tumpang Tindih x Status Kerusakan\nPeta Indikatif Restorasi (PIR) BRG 2016-2020 Tanpa Tumpang Tindih x Detil Prioritas\nPeta Indikatif Restorasi (PIR) BRG 2016-2020 Tanpa Tumpang Tindih x Hutan Alam\nPeta Indikatif Restorasi (PIR) BRG 2016-2020 Tanpa Tumpang Tindih x Jejak Terbakar 2015-2020\nPeta Indikatif Restorasi (PIR) BRG 2016-2020 Dengan Tumpang Tindih Provinsi\nPeta Indikatif Restorasi (PIR) BRG 2016-2020 Dengan Tumpang Tindih x Status Kerusakan\nPeta Indikatif Restorasi (PIR) BRG 2016-2020 Dengan Tumpang Tindih x Detil Prioritas\nPeta Indikatif Restorasi (PIR) BRG 2016-2020 Dengan Tumpang Tindih x Hutan Alam\nPeta Indikatif Restorasi (PIR) BRG 2016-2020 Dengan Tumpang Tindih x Jejak Terbakar 2015-2020",
            "Sebaran Wilayah Adat Terdata 2018 9,3 Juta Ha\nTumpang Tindih Wilayah Adat x Konsesi, PIPPIB, PIAPS\nWilayah Adat x Izin Sawit\nWilayah Adat x Fungsi Ekosistem Gambut\nArea of Interest Food Estate x Wilayah Adat\nWilayah Adat x Hutan Alam\nFEG di Wilayah Adat x Status Kerusakan",
            "Luas FEG\nSebaran FEG Provinsi\nSebaran FEG x Kawasan Hutan\nSebaran FEG x Hutan Alam\nSebaran FEG x Fungsi\nSebaran FEG x Status Kerusakan\nSebaran FEG x Izin dan Konsesi PIPPIB PIAPS Food Estate Wilayah Adat\nSebaran FEG di PIPPIB x Izin dan Konsesi\nSebaran FEG x Jejak Terbakar 2015-2020\nSebaran FEG Detil Area Tanpa Tumpang Tindih\nSebaran FEG Tanpa Tumpang Tindih x Provinsi\nSebaran FEG Detil Area Tanpa Tumpang Tindih x Status Kerusakan\nSebaran FEG Detil Area Tanpa Tumpang Tindih x Area Prioritas Restorasi\nSebaran FEG Detil Area Tanpa Tumpang Tindih x Hutan Alam\nSebaran FEG Detil Area Tanpa Tumpang Tindih x Jejak Terbakar 2015-2020\nSebaran FEG Detil Area Dengan Tumpang Tindih Provinsi\nSebaran FEG Detil Area Dengan Tumpang Tindih x Status Kerusakan\nSebaran FEG Detil Area Dengan Tumpang Tindih x Prioritas\nSebaran FEG Detil Area Dengan Tumpang Tindih x Hutan Alam\nSebaran FEG Detil Area Dengan Tumpang Tindih x Jejak Terbakar 2015-2020\nSebaran FEG Detil Area Dengan Tumpang Tindih x Izin dan Konsesi",
            "Sebaran Izin Sawit di FEG x Detil Fungsi\nSebaran Izin Sawit di FEG x Provinsi\nSebaran Izin Sawit di FEG x Hutan Alam\nSebaran Izin Sawit di FEG x Tutupan Sawit\nSebaran Izin Sawit di FEG x Kawasan Hutan\nSebaran Izin Sawit di FEG x Detil Prioritas Restorasi\nSebaran Izin Sawit di FEG x Target Restorasi\nSebaran Izin Sawit di FEG x Status Kerusakan\nSebaran Izin Sawit di FEG x Jenis Izin\nSebaran Izin Sawit di FEG x Tipe Usaha\nSebaran Izin Sawit di FEG x Status Sertifikasi ISPO dan RSPO\nSebaran Jejak Terbakar 2015-2020 di Izin Sawit di FEG\nSebaran Izin Sawit di FEG x Izin dan Konsesi PIPPIB PIAPS Wilayah Adat",
            "Rekapitulasi SIPONGI Mei 2021 VS Model APT Jan-Mei 2021\nKorelasi SIPONGI Mei 2021 VS Model APT Jan-Mei 2021\nSebaran Area Kumpulan Hotspot Januari-Mei 2021\n10 Provinsi dengan APT Terluas\nAPT x Kawasan Hutan\nAPT x FEG\nAPT x Izin dan Konsesi, PIPPIB, PIAPS, Wilayah Adat\nAPT x PIPPIB\nAPT x Izin Sawit\nAPT x Pabrik Kelapa Sawit",
            "Luas Izin Sawit di Papua dan Papua Barat\nIzin Sawit di Provinsi Papua per Kabupaten\nIzin Sawit di Provinsi Papua Barat per Kabupaten\nIzin Sawit di Papua dan Papua Barat x Sertifikasi ISPO dan RSPO\nIzin Sawit di Papua dan Papua Barat x Tutupan Sawit\nIzin Sawit di Papua dan Papua Barat x Hutan Alam\nIzin Sawit di Papua dan Papua Barat x Jejak Terbakar\nIzin Sawit di Papua dan Papua Barat x Jenis Izin\nIzin Sawit di Papua dan Papua Barat x Tipe Bisnis\nIzin Sawit di Papua dan Papua Barat x PIPPIB x Konsesi\nIzin Sawit di Papua dan Papua Barat x Kawasan Hutan\nIzin Sawit di Papua dan Papua Barat x Fungsi Ekosistem Gambut\nIzin Sawit di Papua dan Papua Barat x Deforestasi\nDeforestasi Hutan Alam 2019-2020 10 Kabupaten Terluas\nDeforestasi Hutan Alam 2019-2020 10 Kabupaten Terluas x Provinsi",
            "Peta Fungsi Ekosistem Gambut Tanpa Tumpang Tindih",
            "Peta Indikatif Restorasi x KHG Prioritas x 6 Izin dan Konsesi x Target Restorasi 2016-2020\nRekomendasi Target Restorasi di 7 Provinsi Prioritas BRGM\nRekomendasi Target Restorasi x Status Kerusakan\nRekomendasi Target Restorasi x Prioritas Restorasi x Fungsi Ekosistem Gambut\nRekomendasi Target Restorasi x Jejak Terbakar 2015-2020\nRekomendasi Target Restorasi x Kawasan Hutan\nRekomendasi Target Restorasi x PIPPIB dan PIAPS\nRekomendasi Target Restorasi x Wilayah Adat x AoI Food Estate\nAnalisis Jejak Terbakar di Peta Indikatif Restorasi (PIR) 2 dan 106 KHG Prioritas\nSebaran Peta Indikatif Restorasi 2 (PIR) Provinsi\nJejak Terbakar di PIR 2 2015-2020\nLuas KHG Prioritas (106 KHG)\nJejak Terbakar di 106 KHG Prioritas",
            "Sebaran Pabrik Kelapa Sawit di Riau dan Kalbar ",
            "Sebaran PIAPS Revisi 4\nSebaran PIAPS Revisi 4 Provinsi\nSebaran PIAPS Revisi 4 x Kawasan Hutan\nSebaran PIAPS Revisi 4 x Hutan Alam\nSebaran PIAPS Revisi 4 Hutan Alam x Kawasan Hutan\nSebaran PIAPS Revisi 4 FEG\nSebaran PIAPS Revisi 4 x FEG x Hutan Alam\nSebaran PIAPS Revisi 4 x FEG x Kawasan Hutan\nSebaran PIAPS Revisi 4 x AoI Food Estate\nSebaran PIAPS Revisi 4 di 4 Provinsi\nSebaran PIAPS Revisi 4 x PIPPIB\nSebaran PIAPS Revisi 4 x Wilayah Adat\nSebaran PIAPS Revisi 4 x Deforestasi Bruto 2011-2020\nSebaran PIAPS Revisi 4 x Jejak Terbakar 2015-2020\nSebaran PIAPS Revisi 4 x APT Januari-Juli 2021\nSebaran PIAPS Revisi 4 x Izin dan Konsesi ",
            "Sebaran Usaha dan Tutupan Sawit\nSebaran Pabrik Kelapa Sawit Radius 25 km\nLuas Tutupan Sawit di Radius 25 km\nLuas Hutan Alam di Radius 25 km\nLuas Ekosistem Gambut di Radius 25 km\nJejak Terbakar di Radius 25 km\nDeforestasi Bruto 2011-2020 di Radius 25 km\nKawasan Hutan di Radius 25 km\nAoI Food Estate di Radius 25 km\nIzin dan Konsesi di Radius 25 km\nPIPPIB dan PIAPS di Radius 25 km\nWilayah Adat di di Radius 25 km\nAPT di Izin Sawit di Radius 25 km",
            "Sebaran Deforestasi Bruto 2011-2020 di Usaha Sawit\nDeforestasi Bruto di Usaha Sawit 2011-2020 per Pulau\nHutan Alam Tersisa di Usaha Sawit Periode 2011-2019 per Pulau",
            "Hutan Alam Belum Terlindungi di Luar Izin dan Konsesi 2021 x Kawasan Hutan\nHutan Alam Belum Terlindungi di Luar Izin dan Konsesi 2021 x Hutan Alam Primer dan Sekunder\nHutan Alam Belum Terlindungi di Luar Izin dan Konsesi 2021 x Provinsi\nHutan Alam Belum Terlindungi di Luar Izin dan Konsesi 2021 x 10 Kabupaten Terluas\nHutan Alam Belum Terlindungi di Luar Izin dan Konsesi 2021 x FEG Gambut dan Mineral\nHutan Alam Belum Terlindungi di Luar Izin dan Konsesi 2021 x FEG\nHutan Alam Belum Terlindungi di Luar Izin dan Konsesi 2021 x AoI Food Estate\nHutan Alam Belum Terlindungi di Luar Izin dan Konsesi 2021 x Wilayah Adat\nHutan Alam Belum Terlindungi di Luar Izin dan Konsesi 2021 x Deforestasi 2011-2020\nHutan Alam Belum Terlindungi di Luar Izin dan Konsesi 2021 x Jejak Terbakar 2015-2020\nHutan Alam Belum Terlindungi di Luar Izin dan Konsesi 2021 x APT Januari-Agustus 2021\nHutan Alam Primer Belum Terlindungi di Luar Izin dan Konsesi 2021 x Provinsi\nHutan Alam Primer Belum Terlindungi di Luar Izin dan Konsesi 2021 x 10 Kabupaten Terluas\nHutan Alam Primer Belum Terlindungi di Luar Izin dan Konsesi 2021 x Hutan Alam\nHutan Alam Primer Belum Terlindungi di Luar Izin dan Konsesi 2021 x Kawasan Hutan\nHutan Alam Primer Belum Terlindungi di Luar Izin dan Konsesi 2021 x FEG Gambut dan Mineral\nHutan Alam Primer Belum Terlindungi di Luar Izin dan Konsesi 2021 x FEG\nHutan Alam Primer Belum Terlindungi di Luar Izin dan Konsesi 2021 x AoI Food Estate\nHutan Alam Primer Belum Terlindungi di Luar Izin dan Konsesi 2021 x Wilayah Adat\nHutan Alam Primer Belum Terlindungi di Luar Izin dan Konsesi 2021 x Deforestasi Bruto 2011-2020\nHutan Alam Primer Belum Terlindungi di Luar Izin dan Konsesi 2021 x Jejak Terbakar 2015-2020\nHutan Alam Primer Belum Terlindungi di Luar Izin dan Konsesi 2021 x APT Jan-Agustus 2021",
            "Hutan Alam Tersisa 2011-2019\nHutan Alam Tersisa 2011-2019 Komposisi per Tahun\nHutan Alam Tersisa 2011-2019 Komposisi per Pulau Besar\nHutan Alam Tersisa 2011-2019 Bali Nusra\nHutan Alam Tersisa 2011-2019 Jawa\nHutan Alam Tersisa 2011-2019 Kalimantan\nHutan Alam Tersisa 2011-2019 Maluku\nHutan Alam Tersisa 2011-2019 Papua\nHutan Alam Tersisa 2011-2019 Sulawesi\nHutan Alam Tersisa 2011-2019 Sumatera\nSelisih Luasan Hutan Alam 2012-2019\nData Deforestasi Bruto 2011-2020\nData Deforestasi Bruto 2011-2020 per Pulau Besar\nData Deforestasi Bruto 2011-2020 ",
            "Usaha Sawit di Kawasan Hutan Data CSO vs GFW\nLuas Usaha Sawit di Kawasan Hutan 7 Juta Ha\nSebaran Usaha Sawit di Kawasan Hutan x Sertifikasi ISPO dan RSPO\nUsaha Sawit di Kawasan Hutan x Tutupan Sawit\nUsaha Sawit di Kawasan Hutan x Tutupan Hutan Alam\nUsaha Sawit di Kawasan Hutan x FEG\nUsaha Sawit di Kawasan Hutan x Wilayah Adat\nUsaha Sawit di Kawasan Hutan x Fungsi Kawasan Hutan\nUsaha Sawit di Kawasan Hutan x PIPPIB dan PIAPS\nUsaha Sawit di Kawasan Hutan x Izin dan Konsesi\nUsaha Sawit di Kawasan Hutan x Hutan Lindung dan Konservasi x IPPKH\nUsaha Sawit di Kawasan Hutan x Hutan Lindung dan Konservasi x IPPKH x Hutan Alam x Gambut x PKH x PSUsaha Sawit di Kawasan Hutan x Jenis Izin dan Tipe Bisnis\nUsaha Sawit di Kawasan Hutan x Deforestasi 2011-2020\nUsaha Sawit di Kawasan Hutan x Jejak Terbakar 2015-2020",
            "Tutupan Sawit di Kawasan Hutan 2020\nTutupan Sawit di Kawasan Hutan x Provinsi\nTutupan Sawit di Kawasan Hutan x FEG\nTutupan Sawit di Kawasan Hutan x Prioritas Restorasi Gambut\nTutupan Sawit di Kawasan Hutan x PIAPS dan PIPPIB\nTutupan Sawit di Kawasan Hutan x Wilayah Adat\nTutupan Sawit di Kawasan Hutan x Izin dan Konsesi \nTutupan Sawit di Kawasan Hutan x PS, IPPKH, PKH\nTutupan Sawit di Kawasan Hutan x Usaha Sawit",
            "Korelasi Data APT VS Sipongi 1 Januari-14 Agustus 2021\nKorelasi Data APT VS Sipongi 1 Januari-14 Agustus 2021 Kalbar, NTB, Riau, NTT\nAkumulasi APT Januari-14 Agustus 2021\nPenambahan APT per Bulan Januari-14 Agustus 2021\nSebaran APT Detil Provinsi\nAPT x Jejak Terbakar 2015-2020\nSebaran APT di Kawasan Hutan\nSebaran APT x Tutupan Lahan\nSebaran APT x FEG\nSebaran APT x AoI Food Estate\nSebaran APT x Wilayah Adat\nSebaran APT x PIPPIB dan PIAPS\nSebaran APT x Izin dan Konsesi",
            "Luas Hutan Alam Belum Terlindungi di Luar Izin dan Konsesi Sulteng \nHutan Alam Belum Terlindungi di Luar Izin dan Konsesi Sulteng x Kawasan Hutan\nHutan Alam Belum Terlindungi di Luar Izin dan Konsesi Sulteng x Deforestasi 2011-2020\nHutan Alam Belum Terlindungi di Luar Izin dan Konsesi Sulteng x Jejak Terbakar 2015-2020\nHutan Alam Belum Terlindungi di Luar Izin dan Konsesi Sulteng x FEG\nHutan Alam Belum Terlindungi di Luar Izin dan Konsesi Sulteng x Hutan Alam\nHutan Alam Belum Terlindungi di Luar Izin dan Konsesi Sulteng x PIPPIB dan PIAPS\nHutan Alam Belum Terlindungi di Luar Izin dan Konsesi Sulteng x Sekitar PIPPIB dan PIAPS\nHutan Alam Belum Terlindungi di Luar Izin dan Konsesi Sulteng x Jumlah Desa",
            "Hutan Alam Belum Terlindungi Sulteng di APL\nHutan Alam Belum Terlindungi Sulteng di APL 40 Lokasi Terluas dalam Satu Bentangan\nKlaster 1 Kabupaten Banggai Laut\nKlaster 2 Kabupaten Banggai\nKlaster 3 Kabupaten Banggai dan Tojo Una-Una\nKlaster 4 Kabupaten Banggai dan Tojo Una-Una dan Morowali Utara\nKlaster 5 Kabupaten Morowali\nKlaster 6 Kabupaten Poso dan Sigi\nKlaster 7 Kabupaten Donggala\nKlaster 8 Kabupaten Buol dan Toli-Toli",
            "Analisis Intact Forest di 19 Lokasi",
            "Hutan Alam Tersisa di Maluku 2019\nKawasan Strategis dan Pola Ruang di RTRW Maluku\nHutan Alam dalam Kawasan Strategis dan Pola Ruang di RTRW Maluku\nHutan Alam di Kawasan Strategis yang Masuk Kepentingan DDLH\nHutan Alam dalam Pola Ruang yang Masuk Arahan Lindung",
            "FEG di luar Izin dan Konsesi, PIAPS dan PIPPIB 2,8 Juta Ha\nFEG di luar Izin dan Konsesi, PIAPS dan PIPPIB 2,8 Juta Ha x Provinsi\nFEG di luar Izin dan Konsesi, PIAPS dan PIPPIB 2,8 Juta Ha x FLEG dan FBEG\nFEG di luar Izin dan Konsesi, PIAPS dan PIPPIB 2,8 Juta Ha x Prioritas Restorasi X Target Restorasi\nFEG di luar Izin dan Konsesi, PIAPS dan PIPPIB 2,8 Juta Ha x Status Kerusakan\nFEG di luar Izin dan Konsesi, PIAPS dan PIPPIB 2,8 Juta Ha x Lahan Gambut dan Mineral\nFEG di luar Izin dan Konsesi, PIAPS dan PIPPIB 2,8 Juta Ha x Tutupan Sawit\nFEG di luar Izin dan Konsesi, PIAPS dan PIPPIB 2,8 Juta Ha x Hutan Alam\nFEG di luar Izin dan Konsesi, PIAPS dan PIPPIB 2,8 Juta Ha x Tutupan Perkebunan\nFEG di luar Izin dan Konsesi, PIAPS dan PIPPIB 2,8 Juta Ha x Deforestasi Bruto 2011-2020\nFEG di luar Izin dan Konsesi, PIAPS dan PIPPIB 2,8 Juta Ha x Jejak Terbakar 2015-2020\nFEG di luar Izin dan Konsesi, PIAPS dan PIPPIB 2,8 Juta Ha x AoI Food Estate\nFEG di luar Izin dan Konsesi, PIAPS dan PIPPIB 2,8 Juta Ha x Wilayah Adat\nFEG di luar Izin dan Konsesi, PIAPS dan PIPPIB 2,8 Juta Ha x Arahan Pemanfaatan Perizinan Berusaha Pemanfaatan Hutan\nFEG di luar Izin dan Konsesi, PIAPS dan PIPPIB 2,8 Juta Ha",
            "HPK Tidak Produktif di Luar PIPPIB dan PIAPS dan di Luar Izin dan Konsesi\nHPK Tidak Produktif di Luar PIPPIB dan PIAPS dan di Luar Izin dan Konsesi x Tutupan Lahan\nHPK Tidak Produktif di Luar PIPPIB dan PIAPS dan di Luar Izin dan Konsesi x Tutupan Sawit\nHPK Tidak Produktif di Luar PIPPIB dan PIAPS dan di Luar Izin dan Konsesi Tanpa FEG\nHPK Tidak Produktif di Luar PIPPIB dan PIAPS dan di Luar Izin dan Konsesi Fokus 5 Tutupan Lahan",
            "Sebaran Sisa Lahan untuk Pengembangan Feedstock Biofuel x Fungsi Kawasan Hutan\nSebaran Sisa Lahan untuk Pengembangan Feedstock Biofuel x Komoditas Eksisting di Sekitarnya",
            "Luas Izin\/Usaha Sawit Saat Ini Tanpa Hutan Alam, FEG, Wilayah Adat, Habitat 15 Spesies, dan yang Sudah Bertutupan Sawit, Fokus Tutupan Lahan yang Dapat Diusahakan, \nSebaran Potensi Lahan yang Dapat Dioptimalisasi\nTumpang Tindih dengan Izin Lain\nDeforestasi Bruto 2011-2020 dan Jejak Terbakar 2015-2020\nTotal Lahan Tersisa 613 ribu Ha",
            "Data SK Perhutanan Sosial yang telah Madani Catat, di kaitkan dengan Kawasan Hutan, Hutan alam Tersisa, Detail Data SK PS, Kaitan dengan Deforestasi, Kaitan dengan IDM ",
            "Data SK Pencabutan Izin selua 5,3 juta ha. Namun data Spasial yang ada di Madani hanya mencakup 3,5 juya ha. Data tersebut selajutnya di kaitkan dengan detail konsesi mana saja yang masuk dalam pencabutan tersebut. Kaitan juga dengan kawasan hutan, Hutan alam tersisa, Food Estate, tutupan lahan, sebaran di tiap Provinsi. Terakhit dikaitkan dengan deforstasi dan jejak terbakar. ",
            "Tim GIS Madani menyusus pemutahiran data terkait hutan dan lahan. Pada sari informasi ini menyajikan setidaknya 5 bahasan cepat terkait spasial. Sari informasi ini mencakup (1) Spasial update Peta Araham Pemanfaatan hutan 2021. (2) Spasial Update Hutan Alam yang belum masuk skema perlindungan dan berada di luar izin serta konsesi eksisting. (3) Spasial update usaha dan tuutpan sawit 2022. (4) Spasial Update penutupan lahan 2020. (5) Spasial update jejak terbakar 2021. ",
            "Pada ulasan ini berisikan gambaran deforestasi 2003-2020 dengan pendetailan di area tumpang tindih lahan dan di area tidak tumpang tidih. Lebih jauh lagi membahas tentang deforestasi yang fokus pada srea yang sebelumnys tutupan hutan alam"
        ];
        foreach ($categories as $i => $val) {
            DB::table('documents')->insert([
                [
                    "category" => $categories[$i],
                    "tags" => $tags[$i],
                    "file_name" => $filenames[$i],
                    "file_source" => $filesources[$i],
                    "year" => $years[$i],
                    "folder" => $links[$i],
                    "doc_description" => $desc[$i],
                    "created_at" => now(),
                    "updated_at" => now()
                ],
            ]);
        }
    }
}
