<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PublicationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $categories = [
            "Hutan Alam",
            "Hutan Alam",
            "Gambut",
            "Sawit",
            "Hutan Alam",
            "Biofuel",
            "C20",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "Sawit",
            "Sawit",
            "Hutan Alam",
            "Hutan Alam",
            "Hutan Alam",
            null,
            null,
            null,
            null,
            null,
            null,
            "Sawit",
            "Hutan Alam",
            "Deforestasi",
            "NDC",
            "Gambut",
            "Karhutla",
            "Hutan Alam, Gambut, Masyarakat Adat",
            "Hutan Alam",
            "Sawit",
            "Sawit",
            "Hutan Alam, Sawit",
            "Hutan Alam, Sawit, Masyarakat Adat",
            "Hutan Alam, Sawit",
            "Hutan Alam",
            "Hutan Alam, Biofuel, NDC",
            "Hutan Alam, Gambut",
            "Deforestasi",
            "Hutan Alam",
            "Pendanaan Iklim & Nilai Ekonomi Karbon",
            "Hutan Alam",
            "Hutan Alam",
            "Hutan Alam, Sawit",
            "Hutan Alam, Sawit",
            "Hutan Alam",
            "Sawit",
            "Hutan Alam",
            "Pendanaan Iklim & Nilai Ekonomi Karbon, REDD+",
            "Perhutanan Sosial",
            "Sawit",
            "Hutan Alam",
            null,
            "Hutan Alam",
            "Hutan Alam",
            null,
            "NDC",
            "Sawit",
            "Sawit",
            "Sawit",
            "Sawit",
            "Sawit",
            "Hutan Alam",
            "Hutan Alam",
            "Hutan Alam",
            "Hutan Alam",
            "Hutan Alam",
            "Hutan Alam",
            "Hutan Alam",
            "Hutan Alam",
            "Sawit",
            "Hutan Alam",
            "Hutan Alam",
            "Hutan Alam",
            "Sawit",
            "Hutan Alam",
            "Hutan Alam",
            "Hutan Alam",
            "Hutan Alam",
            "Hutan Alam",
            "Hutan Alam"
        ];

        $tags = [
            "NEK",
            "NEK, BPDLH",
            "Karhutla, Gambut, FOLU Net Sink, Area Potensi Terbakar, APT",
            "Audit Perizinan Sawit",
            "Moratorium Hutan, Inpres, Net Sink FOLU",
            "BBN, Diversifikasi, Biofuel, RUU Energi Baru Terbarukan, EUU EBT",
            "Adaptasi Mitigasi Inklusif, AFOLU",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "Moratorium Sawit, Hutan Alam, Gambut",
            "ISPO",
            "NDC",
            "Food Estate",
            "UUCK",
            null,
            null,
            null,
            null,
            null,
            null,
            "RAN-KSB",
            "UUCK",
            "NDC",
            "Updated NDC",
            "Restorasi Gambut, BRGM",
            "Sawit, Gambut, PIPPIB, PIAPS",
            "RPJMN",
            "IKN, UUCK",
            "Kemiskinan, Kalbar, Desa Peduli Api",
            "Sawit, Indeks Desa Membangun",
            "UUCK, RUU Minerba, WHO, SVLK, PHPL",
            "ISPO, SVLK, UUCK, RUU MA",
            "UUCK",
            "SVLK, Omnibus Law, Mineral and Coal Bill",
            "REDD+, Rehabilitasi Hutan dan Lahan, Nilai Ekonomi Karbon",
            "Pilkada",
            "Definisi deforestasi,",
            "UUCK, Omnibus Law",
            "BRGM, LoI, Norwegia, Hutan Harapan",
            "Hutan Tanaman Rakyat",
            "KLHK",
            "UUCK",
            "REDD+, Norwegia",
            "REDD+, Norwegia, Proyek Strategis Nasiona;",
            "ISPO, RSPO",
            "UUCK",
            "REDD+, Safeguards",
            "NDC",
            "Moratorium Sawit",
            null,
            null,
            "KLHK",
            "Deklarasi Manokwari, Papua",
            null,
            null,
            "Perizinan Sawit",
            "Moratorium Sawit",
            "Moratorium Sawit",
            "Moratorium Sawit",
            "Moratorium Sawit",
            "Analisis Media",
            "REDD+, BPDLH",
            "Perhutanan Sosial, Hutan Adat",
            "RPJMN, Rasionalisasi Kawasan Hutan",
            "REDD+",
            "REDD+",
            "One Map",
            "BPDLH",
            "Moratorium Sawit",
            "RED II",
            "Reforma Agraria",
            "Pilkada",
            "Moratorium Sawit",
            "Deforestasi",
            "Biofuel",
            "REDD+",
            "REDD+",
            "REDD+",
            "REDD+"
        ];

        $filenames = [
            "Donor Updates: The Position and Role of Indigenous Peoples\nand Local Communities in Carbon Pricing\nImplementation in Indonesia",
            "KKI Warsi_Madani-Policy Brief Nilai Ekonomi Karbon",
            "Mengoptimalkan Pencegahan dan Mitigasi Karhutla di Area Potensi Terbakar yang Tinggi untuk Mencapai Indonesia\nFOLU Net Sink 2030",
            "Fact Sheet Potensi Penerimaan Negara Dari Audit Perusahaan Sawit",
            "Policy Brief Memperkuat Inpres Moratorium Hutan untuk Mencapai Target Net Sink FOLU",
            "MENDORONG PRINSIP KEBERLANJUTAN DAN DIVERSIFIKASI BAHAN BAKU BAHAN BAKAR NABATI DALAM RUU ENERGI BARU TERBARUKAN_Madani et al",
            "C20 Policy Briefs_WG ECE C20",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "Mengoptimalkan Perlindungan Hutan Alam dan Ekosistem Gambut Pasca Moratorium Sawit",
            "Analisis Permentan ISPO",
            "NDC Progress Report: Menakar Kemajuan Penurunan Emisi di Sektor Kehutanan_final",
            "Menakar Ancaman terhadap Hutan Alam dan Gambut di Balik Pengembangan Food Estate",
            "Pandangan Kritis UU 11 Tahun 2020 tentang Cipta Kerja",
            null,
            null,
            null,
            null,
            null,
            null,
            "Analisa Inpres No. 6 Tahun 2019 Kelapa Sawit Berkelanjutan (RAN KSB)",
            "Tinjauan Risiko RUU Cipta Kerja terhadap Hutan Alam dan Pencapaian Komitmen Iklim Indonesia",
            "Updates on Deforestation and PIPPIB",
            "Masukan CSO untuk Dokumen Updated NDC",
            "Analisis Perpres 120 Tahun 2020 tentang BRGM",
            "Hotspots Invasion Review of the 2019 Forest and Land Fires",
            "Hutan, Gambut, Masyarakat Adat dan Perubahan Iklim dalam Perencanaan Pembangunan Indonesia 2020-2024",
            "Indonesian Political Situation January 2020",
            "Madani Insight Vol 3",
            "Madani Insight Vol 5",
            "Madani Monthly Political Update April Mei 2020 - RUU Cipta Kerja, RUU Minerba, WHO Bicara Sawit, dan Permendag No. 15 Tahun 2020",
            "Madani Monthly Political Update Mar 2020 - ISPO, SVLK, Omnimbus Law, dan RUU Masyarakat Adat Maret 2020",
            "Madani Monthly Updates on Indonesia Political Situation Feb 2020",
            "MADANI_S UPDATE_ April May 2020",
            "MADANI_S UPDATE_June 2020",
            "Nasib Hutan dan Gambut Indonesia di Tengah Pusaran Pilkada Serentak 2020",
            "Navigating The Deforestation Maze",
            "Risk Assessment of Job Creation Bill on Natural Forest",
            "Penanganan Covid-19 Hutan Harapan dan Peraturan Nilai Ekonomi Karbon",
            "Pendapat Hukum Peraturan Menteri No. P.11 Tahun 2020 Tentang Hutan Tanaman Rakyat",
            "Pendapat Hukum Perpres Nomor 92 Tahun 2020 Tentang KLHK",
            "Political Updates April Mei 2020",
            "Political Updates February 2020",
            "Political Updates Juni 2020",
            "Presidential Regulation 44 Year 2020 on ISPO",
            "Masukan RPP UU CK Bidang Kehutanan",
            "REDD Results Based Payment - Where are the safeguards",
            "Social Forestry Can Help Indonesia Meet Its Climate Pledge",
            "Shadow Report: Ke Mana Arah Implementasi Moratorium Sawit Berjalan",
            "Madani's Update: Tren dan Prospek Pengelolaan Sumber Daya Alam di Indonesia",
            "Madani's Update: Pedoman Penyelenggaraan Pendampingan Masyarakat Perhutanan Sosial",
            "Analisis Hukum Permen Lingkungan Hidup dan Kehutanan No. P.10\/2019",
            "Sinkronisasi Peta Jalan Nol Deforestasi Papua Bara dengan Deklarasi Manokwari",
            "Madani Updates: Understanding What FREL for Subnational Level Means for Forests for Subnational Level ",
            "(RFN Updates Policy Development Jan-Mar 2019) NDC developments in the forestry sector - Indonesia",
            "Madani's Update: Analisis Permentan No.5 Tahun 2019 Tentang Tata Cara Perizinan Berusaha Sektor Pertanian",
            "Laporan 1 Tahun Inpres Moratorium Sawit",
            "Analisis Substansi Inpres Moratorium Sawit No. 8 2018",
            "Policy Brief Membumikan Moratorium dan Evaluasi Moratorium Sawit",
            "Policy Brief Making Palm Oil Moratorium and Evaluation of Palm Oil Licenses Work on the Ground",
            "Madani's Update Summary of Media Analysis 6-19 May 2019",
            "LH-FUND AS REDD+ FUNDING INSTRUMENT: IMPORTANT CONSIDERATIONS TO MAKE IT A FAIR AND INCLUSIVE FUNDING INSTRUMENT",
            "Madani's Update Customary Forest",
            "POLICY BRIEF Rasionalisasi Penataan dan Penggunaan Kawasan Hutan Indonesia",
            "REDD+ Update Report January I 2018 Regulations Regarding NDC Implementation",
            "Sorotan Kondisi Hutan Indonesia",
            "REDD+ Update Report: Regulations concerning Access to Geospatial Data and\nInformation in One Map Policy Acceleration",
            "REDD+ Update Report: Environment Fund Management Presidential Regulation No. 77 Year 2018 on Environment Fund Management",
            "REDD+ Update Report: The Palm Oil Moratorium Presidential Instruction No. 8 Year 2018 on Suspension and Evaluation of Palm Oil Plantation Licenses and Improvement of Palm Oil Plantation Productivity",
            "REDD+ Update Report: EU’s RED II Revision: Trialogue Result and Reactions in\nIndonesian Media",
            "REDD+ Update Report: Agrarian Reform Presidential Regulation No. 86 Year 2018 on Agrarian Reform",
            "REDD+ Update Report “Regional Elections and the Fate of Forests and Peatland",
            "Update Report Rancangan Instruksi Presiden untuk Penundaan dan Evaluasi Perizinan Perkebunan Kelapa Sawit dan Peningkatan Produktivitas Perkebunan Kelapa Sawit",
            "REDD+ Update Report Mengurai Benang Kusut Penghitungan Deforestasi Indonesia",
            "REDD+ Update Report The Biofuel Polemic",
            "REDD+ Update Report Palm Oil Moratorium” Draft Presidential Instruction on the Suspension and Evaluation of Palm Oil Plantation Licenses and Improvement of Palm Oil Plantation Productivity",
            "REDD+ Update Report Regulation of Minister of Environment and Forestry No. 70\/2017 on The Procedure of Implementation for Reducing Emissions from\nDeforestation and Forest Degradation, Role of Conservation,Sustainable Management of Forest, and Enhancement of Carbon Stocks",
            "Madani Update Reports Compilation 2017",
            "Madani Update Reports Compilation 2016"
        ];

        $filesources = [
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani dalam C20",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Koalisi Moratorium Sawit",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Koalisi Moratorium Sawit",
            "Madani",
            "Koalisi Moratorium Sawit",
            "Koalisi Moratorium Sawit",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani"
        ];

        $years = [
            2022,
            2022,
            2022,
            2022,
            2022,
            2022,
            2022,
            2022,
            2022,
            2022,
            2022,
            2022,
            2022,
            2022,
            2021,
            2021,
            2021,
            2021,
            2021,
            2021,
            2021,
            2021,
            2021,
            2021,
            2021,
            2020,
            2020,
            2020,
            2020,
            2020,
            2020,
            2020,
            2020,
            2020,
            2020,
            2020,
            2020,
            2020,
            2020,
            2020,
            2020,
            2020,
            2020,
            2020,
            2020,
            2020,
            2020,
            2020,
            2020,
            2020,
            2020,
            2019,
            2019,
            2019,
            2019,
            2019,
            2019,
            2019,
            2019,
            2019,
            2019,
            2019,
            2018,
            2018,
            2018,
            2019,
            2019,
            2019,
            2018,
            2018,
            2018,
            2018,
            2018,
            2018,
            2018,
            2018,
            2018,
            2018,
            2018,
            2018,
            2018,
            2018,
            2017,
            2016
        ];

        $links =
            [
                "https://drive.google.com/file/d/12N2msD5CfAxX0LmmlWOuNDfHEv7vsmWp/view?usp=sharing",
                "https://drive.google.com/file/d/1pSD-Wnl3X6WNNk1k5ZUEnaiv7zaB1SQY/view?usp=sharing",
                "https://drive.google.com/file/d/1UBDfcLRDFlNx7dfXwlfCRSXy4HShHqGC/view?usp=sharing",
                "https://drive.google.com/file/d/1EfmkZVTJ5VWojxV8aLl062hL2N383prn/view?usp=sharing",
                "https://drive.google.com/file/d/1nj2oWj3-MCYufHPWSk6NYRXZHfrjQm7q/view?usp=sharing",
                "https://madaniberkelanjutan.id/2022/02/14/mendorong-prinsip-keberlanjutan-dan-diversifikasi-bahan-baku-bahan-bakar-nabati-dalam-ruu-energi-baru-terbarukan",
                "https://drive.google.com/drive/folders/1bmrQFLU7bjQNn-cCifanjdGgVerG5R7x?usp=sharing",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "https://drive.google.com/file/d/1gvJnfHlwrxQBFlmNUM4OeGZV9FHQMoyp/view?usp=sharing",
                "https://drive.google.com/file/d/1c_Mgdzrjt42sJyAUbZGwI0qyTdhUCoEB/view?usp=sharing",
                "https://drive.google.com/file/d/1dGhfcuppHE6R7_Lt6FQx8J1ZDnwlXvr5/view?usp=sharing",
                "https://drive.google.com/file/d/1rk_Le3KS_Rf409P3WFmC62u_sF6W9yrh/view?usp=sharing",
                "https://drive.google.com/file/d/1z9QmrYcvzvtnPSMCcupzhviJwPD7jkLH/view?usp=sharing",
                "",
                "",
                "",
                "",
                "",
                "",
                "https://drive.google.com/file/d/1DqSofqz1y8lKm-XOL8_kIwd13jkyiYVn/view?usp=sharing",
                "https://drive.google.com/file/d/1rApIollmuc8wIPrARcujePAhT9adFjmP/view?usp=sharing",
                "https://drive.google.com/file/d/1l65ZNVZaPUf31ybNuWC73iMWV20jL1Xm/view?usp=sharing",
                "https://drive.google.com/file/d/1GlhHOhuEQBSHPci3x1P37JtYS2wqTYvX/view?usp=sharing",
                "https://drive.google.com/file/d/10h2kfCCiCXW1S6q3z9dXWifTcZAxc03B/view?usp=sharing",
                "https://drive.google.com/file/d/1ks1DWK2ocRIouQEmaMjots0ONfH7MRw7/view?usp=sharing",
                "https://drive.google.com/file/d/1tHOTfEwJp2A7gDihbwA0GCjHm-oY9Fjb/view?usp=sharing",
                "https://drive.google.com/file/d/13rOmJpPDBWPwg8-fyxxPQUmc9XKLykNB/view?usp=sharing",
                "https://drive.google.com/file/d/1XAlXL0ghsrwsVMlV51JLgHKWmr7u_TvJ/view?usp=sharing",
                "https://drive.google.com/file/d/1wFzRTgwqsVb402bb_Fn-mmeY1IheHEY5/view?usp=sharing",
                "https://drive.google.com/file/d/1gTqtuP0MBosd3FO3TEh1gwFXdL5AsNiL/view?usp=sharing",
                "https://drive.google.com/file/d/1WNc_N36JXIaewP4kKYjt-zjPDj3O5WbL/view?usp=sharing",
                "https://drive.google.com/file/d/196orz0tQ-NzcCw-gJemRZWqa0eLIA3m0/view?usp=sharing",
                "https://drive.google.com/file/d/1gExSQjgq0lsZlCNYM8woVOlBWunDGr6c/view?usp=sharing",
                "https://drive.google.com/file/d/1D0VGfxKLZmvnBq94hdF4IrekfXOGeeYL/view?usp=sharing",
                "https://drive.google.com/file/d/1FB7oB4-wcnb0Rp8G_9mVsT9uM6Yqjpv_/view?usp=sharing",
                "https://drive.google.com/file/d/1YFnb7wBuyJrvUZLMeQ-3AGjefxUj82Yz/view?usp=sharing",
                "https://drive.google.com/file/d/1c1-lftYJiD-ygTIQEusY4kBWAiOJLjm3/view?usp=sharing",
                "https://drive.google.com/file/d/1WR4oziHZyJSCMkQmYKPQ6pmq0shAFt_g/view?usp=sharing",
                "https://drive.google.com/file/d/1X9boqXprV9_YvkoDcMizBYB_yC8dO6j_/view?usp=sharing",
                "https://drive.google.com/file/d/1tlFRqMuaCM-v8HHmDPld_Swn3i9BqbzN/view?usp=sharing",
                "https://drive.google.com/file/d/1gTqtuP0MBosd3FO3TEh1gwFXdL5AsNiL/view?usp=sharing",
                "https://drive.google.com/file/d/196orz0tQ-NzcCw-gJemRZWqa0eLIA3m0/view?usp=sharing",
                "https://drive.google.com/file/d/12zpUaD9Oo15S1W4silzfm03HEy6RnaCf/view?usp=sharing",
                "https://drive.google.com/file/d/1R0DRXsbSPqy9T2ibSd7tWF173umHQWyz/view?usp=sharing",
                "https://drive.google.com/file/d/1wJnLpTSvvwRO44gE9Aami6I8H61XBX5g/view?usp=sharing",
                "https://drive.google.com/file/d/107ABIpLlhpnwEdNI4Or4Z7La_9ZmqMzt/view?usp=sharing",
                "https://drive.google.com/file/d/1VpTd7c5lVfzteb_bICnJmsffd2Pu5gYL/view?usp=sharing",
                "https://drive.google.com/file/d/1iHWqhA7C13zo05Bqo6vg2KgWthTer_oU/view?usp=sharing",
                "https://drive.google.com/file/d/1tlyz7nJgpoVldw4dzS0g2YpRvVfXPDiW/view?usp=sharing",
                "https://drive.google.com/file/d/17JdTjlKN2SkvQXou65avEovHv61-m5un/view?usp=sharing",
                "https://drive.google.com/file/d/1os2RBOxiPa0PTFUjoNi4nuT-7IHRtIG7/view?usp=sharing",
                "https://drive.google.com/file/d/17Xii5gVYKQFlRuM3x7-MD6SyvMfH30ah/view?usp=sharing",
                "https://drive.google.com/file/d/1Nu-jX3K8rudn6syin23IBp--x4rTd9Kg/view?usp=sharing",
                "https://drive.google.com/file/d/17a-H5Si6kOlRPgM-lZJJvXDap_JVMnEo/view?usp=sharing",
                "https://drive.google.com/file/d/1egaHVxlZngRMiGEMn3xKkjW4zkCFVheV/view?usp=sharing",
                "https://drive.google.com/file/d/1E8cA2q_QJDV4Fh7L0VZLc0rinedjThtU/view?usp=sharing",
                "https://drive.google.com/file/d/1WN-dsTAzEHNmT_xxnXFdWxFt2Z57k1A0/view?usp=sharing",
                "https://drive.google.com/file/d/1jmmF7Mc4cqmDS300ruNCDDIKTw1Iy0Ot/view?usp=sharing",
                "https://drive.google.com/file/d/1qXNIEClrTYj5QPFfCgZtH4Bx9cktTz-T/view?usp=sharing",
                "https://drive.google.com/file/d/1qV1Ib6nBAfo4xlMa07eA8Nx5EqCy1zBU/view?usp=sharing",
                "https://drive.google.com/file/d/1gE8GFdSN-tsFl73nA-SmlLXNsHnjVah5/view?usp=sharing",
                "https://drive.google.com/file/d/11ClBhv84QfJNhZg59m3sgxoRZUeY5GN2/view?usp=sharing",
                "https://drive.google.com/file/d/1Ily5ZqpE5_h_Qxbpjjuax4leFQg6T5Sl/view?usp=sharing",
                "https://drive.google.com/file/d/1n1-Rc3LcHud01iTySgi0n85s4EKNvGUs/view?usp=sharing",
                "https://drive.google.com/file/d/1VMN147MCD-D3RAD3yav5ZOXWKxYwG4l8/view?usp=sharing",
                "https://drive.google.com/file/d/1KmJ5rqon3VJyenQHawF59FKYWgpXBWlP/view?usp=sharing",
                "https://drive.google.com/file/d/18H4h7nB8UrlLCUFwePknTOXC6SA8C4TO/view?usp=sharing",
                "https://drive.google.com/file/d/1duhSolXKU0SJyNPs5k5PrMkxp7JAOgVZ/view?usp=sharing",
                "https://drive.google.com/file/d/1gGboDopkxdJznexZhjm0mV-zgckVbxaz/view?usp=sharing",
                "https://drive.google.com/file/d/13I-lp7PvbSNQfIeQNOrP4arA2Td4Td8-/view?usp=sharing",
                "https://drive.google.com/file/d/10ldG6CY7NA8Emd958B1rFH-uNYm3gnF0/view?usp=sharing",
                "https://drive.google.com/file/d/1k2Am2STnp3uXW7P-hTr7Zz-YCH-xKnhS/view?usp=sharing",
                "https://drive.google.com/file/d/1GVTuA4qUeLX2_bYt3Bv7pSxEOuzUaGVM/view?usp=sharing",
                "https://drive.google.com/file/d/1EI-vQL5cwMLSL2GS86xQR9wEqlhcpgqs/view?usp=sharing",
                "https://drive.google.com/file/d/1wUNPNmlfn0ixy9W4lzmzDJ5sdtlLkveN/view?usp=sharing",
                "https://drive.google.com/file/d/11bG-e54M-YNtXf1EHPpuorok-T7inm2t/view?usp=sharing",
                "https://drive.google.com/file/d/1o0S5JNUaCIc3EZrtLEOX9cpmY25Op8bF/view?usp=sharing",
                "https://drive.google.com/file/d/1PCvf1HjUGlmfTOKQvx30h5z0fhLRZVBn/view?usp=sharing",
                "https://drive.google.com/file/d/1pyN5OC1D1YjRdtt-Uf9jRvcZBOBH0mRi/view?usp=sharing"
            ];

        $desc = [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "Sawit di Kawasan Hutan, Risiko Ekspansi Izin Sawit di Kawasan Hutan, Penyelesaian Kegiatan Usaha Sawit yang Telah Terbangun di Kawasan Hutan, Sanksi Pidana vs Sanksi Administratif, Tipologi Penyelesaian Keterlanjuran",
            "Analisis Peraturan Menteri Pertanian No. 38 Tahun 2020 tentang Penyelenggaraan Sertifikasi Perkebunan Berkelanjutan Indonesia\nTata cara permohonan sertifikasi ISPO\nPrinsip dan Kriteria Permentan 38\/2020 dibandingkan dengan Permentan 11\/2015",
            "ANALISIS KEBIJAKAN TERKAIT PENCAPAIAN NDC, PENCAPAIAN NDC YANG DILAPORKAN, INISIATIF YANG BERPOTENSI MEMBANTU PENCAPAIAN NDC, ",
            "Food Estate sebagai Solusi Masalah Pangan\nIndonesia?\nKarpet Merah Kebijakan untuk Food Estate\nHutan Alam dan Lahan Gambut di Area of Interest Food Estate (Papua, Kalteng, Sumut,Sumsel)\nPotensi Nilai Kayu dari Hutan Alam dalam AOI Food Estate\nFood Estate dan Safeguards Tersisa\nIndeks Ketahanan Pangan 34 Provinsi",
            "Klaster Perlindungan Dan Pengelolaan Lingkungan Hidup\nKlaster Pengelolaan Tata Ruang\nKlaster Kehutanan dan Gambut\nKlaster Perkebunan",
            null,
            null,
            null,
            null,
            null,
            null,
            "Ruang lingkup, mandat, program, dan kegiatan dalam RAN KSB: 1) Pembentukan Tim RAN KSB, 2) Penguatan data dasar sawit, 3) Peningkatan kapasitas dan kapabilitas pekebun, 4) Pengelolaan dan pemantauan lingkungan, 5) Pembangunan infrastruktur, 6) Pemanfaatan sawit sebagai energi terbarukan, 7) Penyelesaian status perkebunan lahan sawit dan konflik agraria, 8) Peningkatan kepatuhan hukum, 9) Diplomasi internasional\nCatatan dan rekomendasi untuk RAN KSB 2019-2024",
            "Risiko UU Cipta Kerja terhadap hutan alam dan DAS",
            "Indonesia’s Deforestation Rate 2019\nIndicative Map of Permanent Forest Moratorium (PIPPIB) 2020\nForest Fire 2019 \nSocial Forestry Realization May 2019\nUpdated Nationally Determined Contribution (NDC) 2020 ",
            null,
            "Kondisi Gambut Indonesia Terkini\nTelisik Ekosistem Gambut di Area Izin dan Konsesi\nTelisik Ekosistem Gambut di PIPPIB, PIAPS, dan Wilayah Adat\nTarget Restorasi BRGM dan Komitmen Iklim Indonesia\nBRGM dan Pembelajaran Restorasi Gambut 2016-2020",
            "Review of 2019 fires: 1) land cover, 2) peat ecosystem, 3) newly-burned areas, 4) most affected provinces, 5) fires in protected areas, PIPPIB, PIAPS, 6) fires in palm oil and other permits, 7) Fire-Prone Areas",
            "Sorotan RPJMN 2020-2024 terkait: 1) Hutan alam dan kawasan lindung, 2) hutan di lahan gambut, 3) restorasi gambut, 4) rehabilitasi hutan dan lahan, 5) karhutla, 6) tingkat dan intensitas emisi, 7) major projects dan proyek strategis nasional, 8) pembangunan di Papua, 9) perhutanan sosial dan reforma agraria, 10) masyarakat adat ",
            "MA Perintahkan Jokowi Cabut Aturan Hutan Lindung Bisa Jadi Perkebunan.Bentuk Pemerintahan Untuk Ibu Kota Baru\nOmnibus Law dan Perlindungan Lingkungan Hidup\nPenangkapan Editor Mongabay.com.",
            "Sawit dan Kemiskinan Masyarakat Kalimantan Barat\nLuas dan Produktivitas Sawit Kalimantan Barat\nRekomendasi Desa Peduli Api Bagi Kalimantan Barat",
            "Perusahaan Sawit dan Kemandirian Desa di Kalbar (Antara Data & Fakta)\nKontribusi Perusahaan Sawit Pada Pembangunan Desa di Kalbar\nPenyebab Rendahnya Nilai Indeks Desa Membangun yang Bersinggungan dengan Lokasi HGU",
            "Perkembangan RUU Cipta Kerja\nRUU Minerba Disahkan\nWHO Bicara Sawit\nPermendag No. 15 Tahun 2020 yang Menghapus Kewajiban V-Legal\nDicabut, Permen PHPL dan SLK akan Direvisi\\",
            "Pemerintah Terbitkan Perpres tentang ISPO\nMenteri Perdagangan Terbitkan Permendag tentang Ketentuan Ekspor\nProduk Industri Kehutanan\nStrategi Penanganan Ekonomi Menghadapi Dampak Covid-19\nPembahasan RUU Cipta Kerja dan RUU Masyarakat Adat di Tengah\nPandemi Covid",
            "Pemutusan Kerja Sama Kementerian Lingkungan Hidup dan Kehutanan\ndengan WWF Indonesia\nIsu Keamanan Pangan dari Sawit Indonesia\nPerkembangan Omnibus Law RUU Cipta Kerja",
            "Regulation that Undermined Timber Legality Verification System (SVLK) Revoked\nOmnibus Law\/Job Creation Bill Discussion Continues\nMineral and Coal Revision Bill Signed into Law",
            "REDD+ Results-Based Payment: Norway and Green Climate Fund\nGovernment Regulation on Forest Rehabilitation and Reclamation (PP 26\/2020)\nEconomy Recovery Plan (incl. Biodiesel Subsidy)\nFood Estate on Peatland and Other National Strategic Projects\nDraft Presidential Regulation on Carbon Pricing to Attain NDC",
            "Hutan dan gambut di Provinsi dan Kabupaten peserta Pilkada Serentak 2020\nRusaknya hutan dan bencana\nKewenangan pemerintah daerah dalam menentukan nasib hutan dan gambut",
            "Forest definitions, deforestation, calculation methodologies, natural forest loss, tree cover loss, FREL",
            "Risks of Omnibus Bill to natural forests",
            "Komite Penanganan Covid-19 dan Pemulihan Ekonomi Nasional (Perpres\n82\/2020)\nNasib Badan Restorasi Gambut\nKelanjutan Kerja Sama Indonesia-Norwegia terkait REDD+\nRencana Peraturan Nilai Ekonomi Karbon\nLaporan Koalisi Masyarakat Adat kepada Komite PBB untuk Penghapusan\nDiskriminasi Rasial\nAncaman terhadap Hutan Harapan di Jambi dan Sumatra Selatan",
            "Perubahan pengaturan terkait Hutan Tanaman Rakyat",
            "Penguatan dan Pelemahan Kewenangan KLHK\ndi Perpres 92\/2020",
            "Perkembangan RUU Cipta Kerja \nRUU Minerba Disahkan\nWHO Bicara Sawit \nPermendag No. 15 Tahun 2020 yang Menghapus Kewajiban V-Legal Dicabut, Permen PHPL dan SLK akan Direvisi",
            "Isu Keamanan Pangan dari Sawit Indonesia\nPerkembangan Omnibus Law RUU Cipta Kerja\nPerkembangan Pembahasan Revisi UU Minerba",
            "Dana Insentif REDD+ Norwegia\nPembangunan Rendah Karbon di Fase New Normal \nPresiden Teken PP perihal Rehabilitasi dan Reklamasi Hutan\nSkema Pemulihan Ekonomi NasionalPemerintah Mengusulkan 89 Proyek Strategis Nasional",
            "Highlights of Presidential Regulation No. 44\/2020 2\nISPO Certification System: Now and then\nCivil society concerns\nISPO vs RSPO",
            null,
            "The Emissions Reduction Report\nSafeguards",
            "Potential of social forestry for NDC\nCalculating Contributions of Social Forestry to NDC:\nCase Study of Bukit Barisan Forest Management Unit in West \nSumatra\nCommunity REDD+ Project in Bujang Raba\nLandscape",
            "Perkembangan dan Capaian\n1. Tingkatan Nasional 5\n2. Tingkatan Daerah 8\na) Provinsi Papua 10\nb) Provinsi Papua Barat 11\nc) Provinsi Sulawesi Selatan 11\nd) Kabupaten Banyuasin, Provinsi Sumatera Selatan 12\ne) Kabupaten Gorontalo, Provinsi Gorontalo 13\nf) Kabupaten Buol, Provinsi Sulawesi Tengah 13\ng) Kabupaten Sanggau, Provinsi Kalimantan Barat 14\nD. Studi Kasus di Lapangan 15\nE. Tantangan Pelaksanaan 28",
            "1. LINGKUNGAN HIDUP DAN MASYARAKAT ADAT DALAM VISI-MISI PRESIDEN 2019-\n2024\n2. OMNIBUS LAW\n3. PELEMAHAN KPK\n4. KABINET INDONESIA MAJU\n5. KOMPOSISI DPR\/MPR 2019\/2024\n6. WACANA MENGHIDUPKAN KEMBALI GBHN\n7. PEMINDAHAN IBU KOTA DAN WACANA PEMEKARAN PAPUA.\n8. RELASI PRESIDEN JOKO WIDODO DAN WAKIL PRESIDEN MA’RUF AMIN DENGAN\nAKTOR-AKTOR INDUSTRI EKSTRAKTIF..",
            "Kerangka regulasi \nJenis dan ruang lingkup pendampingan\nSumber tenaga pendamping\nRuang lingkup kegiatan pendampingan\nKewenangan, hak, kewajiban, tanggung jawab pemerintah\nSinergi dan kolaborasi multipihak dalam pendampingan\nTata laksana pendampingan perhutanan sosial \nPemetaan calon tenaga pendamping\nPelatihan\/pembekalan calon tenaga pendamping\nPenjaringan calon tenaga pendamping\nPenataan dan penetapan tenaga pendamping\nPembiayaan pendampingan\nMonitoring dan Evaluasi\nPelaporan",
            null,
            null,
            null,
            "NDC implementation update\nREDD+ implementation update\nProgress of forestry mitigation policies implementation\nForest moratorium\nPalm oil moratorium\nPeatland restoration\nSocial forestry\nPolitical dynamics",
            "Dampak Permentan 5\/2019 terhadap tahapan perizinan perkebunan kelapa sawit............ 4\nPotensi implikasi Permentan 5\/2019.................................................................................... 7\nImplikasi terhadap tata kelola perkebunan sawit, hutan, dan gambut................................. 8\nImplikasi terhadap smallholder dan hak masyarakat........................................................... 8\nImplikasi terhadap pelaksanaan moratorium sawit..............................................................10",
            "Satu tahun implementasi moratorium sawit, implementasi Inpres No. 8 Tahun 2018 di tingkat nasional, perkembangan lokal dan daerah, konflik agraria perkebunan sawit di Kawasan Hutan, peningkatan produktivitas petani, perkebunan sawit di Kawasan Hutan (Papua, Kalbar, Kaltim, Sumsel, Kalteng), ",
            null,
            "Rekomendasi masyarakat sipil untuk implementasi moratorium sawit",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            "ENG",
            null,
            "IND",
            null,
            null,
            null
        ];



        foreach ($categories as $i => $val) {
            DB::table('publications')->insert([
                [
                    "category" => $categories[$i],
                    "tags" => $tags[$i],
                    "file_name" => $filenames[$i],
                    "file_source" => $filesources[$i],
                    "year" => $years[$i],
                    "folder" => $links[$i],
                    "doc_description" => $desc[$i],
                    "created_at" => now(),
                    "updated_at" => now()
                ],
            ]);
        }
    }
}
