<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PublicationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $categories = [
            "Sawit",
            "Sawit",
            "Sawit",
            "Gambut",
            "Karhutla",
            "Hutan Alam, Gambut, Masyarakat Adat",
            "Hutan Alam",
            "Sawit",
            "Sawit",
            "Hutan Alam, Sawit",
            "Hutan Alam, Sawit, Masyarakat Adat",
            "Hutan Alam, Sawit",
            "Hutan Alam",
            "Hutan Alam, Biofuel, NDC",
            "Pendanaan Iklim & Nilai Ekonomi Karbon, REDD+",
            "Hutan Alam, Masyarakat Adat",
            "Hutan Alam",
            "Hutan Alam, Gambut",
            "Deforestasi",
            "Hutan Alam",
            "Pendanaan Iklim & Nilai Ekonomi Karbon",
            "Hutan Alam",
            "Hutan Alam",
            "Hutan Alam, Sawit",
            "Hutan Alam, Sawit",
            "Hutan Alam",
            "Sawit",
            "Pendanaan Iklim & Nilai Ekonomi Karbon, REDD+",
            "Hutan Alam",
            "Perhutanan Sosial",
            "Hutan Alam",
            "Deforestasi",
            "Hutan Alam",
            "Hutan Alam",
            "Sawit",
            "NDC",
            "Hutan Alam",
            "NDC"
        ];

        $tags = [
            "RAN-KSB",
            "ISPO",
            "ISPO",
            "Restorasi Gambut, BRGM",
            "Sawit, Gambut, PIPPIB, PIAPS",
            "RPJMN",
            "IKN, UUCK",
            "Kemiskinan, Kalbar, Desa Peduli Api",
            "Sawit, Indeks Desa Membangun",
            "UUCK, RUU Minerba, WHO, SVLK, PHPL",
            "ISPO, SVLK, UUCK, RUU MA",
            "UUCK",
            "SVLK, Omnibus Law, Mineral and Coal Bill",
            "REDD+, Rehabilitasi Hutan dan Lahan, Nilai Ekonomi Karbon",
            "FPIC, Safeguards, FREL",
            "RKP 2021",
            "Food Estate",
            "Pilkada",
            "Definisi deforestasi,",
            null,
            "BRGM, LoI, Norwegia, Hutan Harapan",
            "Hutan Tanaman Rakyat",
            "KLHK",
            "UUCK",
            "REDD+, Norwegia",
            "REDD+, Norwegia, Proyek Strategis Nasiona;",
            "ISPO, RSPO",
            "REDD+, Safeguards",
            "UUCK, Omnibus Law",
            "NDC",
            "UUCK",
            "NDC",
            "KLHK",
            "Deklarasi Manokwari, Papua",
            "Moratorium Sawit",
            "Updated NDC",
            "UUCK",
            null
        ];

        $filenames = [
            "Analisa Inpres No. 6 Tahun 2019 Kelapa Sawit Berkelanjutan (RAN KSB)",
            "Analisis Permentan ISPO",
            "Diplomat Brief ISPO",
            "Analisis Perpres 120 Tahun 2020 tentang BRGM",
            "Hotspots Invasion Review of the 2019 Forest and Land Fires",
            "Hutan, Gambut, Masyarakat Adat dan Perubahan Iklim dalam Perencanaan Pembangunan Indonesia 2020-2024",
            "Indonesian Political Situation January 2020",
            "Madani Insight Vol 3",
            "Madani Insight Vol 5",
            "Madani Monthly Political Update April Mei 2020 - RUU Cipta Kerja, RUU Minerba, WHO Bicara Sawit, dan Permendag No. 15 Tahun 2020",
            "Madani Monthly Political Update Mar 2020 - ISPO, SVLK, Omnimbus Law, dan RUU Masyarakat Adat Maret 2020",
            "Madani Monthly Updates on Indonesia Political Situation Feb 2020",
            "MADANI_S UPDATE_ April May 2020_English",
            "MADANI_S UPDATE_June 2020_mini updates",
            "Membedah Penggunaan Dana RBP REDD dari GCF(2)",
            "Menakar Agenda Perlindungan dan Pengelolaan Hutan Alam Dalam RKP 2021",
            "Menakar Ancaman terhadap Hutan Alam dan Gambut di Balik Pengembangan Food Estate",
            "Nasib Hutan dan Gambut Indonesia di Tengah Pusaran Pilkada Serentak 2020",
            "Navigating The Deforestation Maze",
            "Pandangan Kritis UU 11 Tahun 2020 tentang Cipta Kerja",
            "Penanganan Covid-19 Hutan Harapan dan Peraturan Nilai Ekonomi Karbon",
            "Pendapat Hukum Peraturan Menteri No. P.11 Tahun 2020 Tentang Hutan Tanaman Rakyat",
            "Pendapat Hukum Perpres Nomor 92 Tahun 2020 Tentang KLHK",
            "Political Updates April 2020",
            "Political Updates February 2020",
            "Political Updates Juni 2020",
            "Presidential Regulation 44 Year 2020 on ISPO",
            "REDD Results Based Payment - Where are the safeguards",
            "Risk Assessment of Job Creation Bill on Natural Forest",
            "Social Forestry Can Help Indonesia Meet Its Climate Pledge",
            "Tinjauan Risiko RUU Cipta Kerja terhadap Hutan Alam dan Pencapaian Komitmen Iklim Indonesia",
            "Updates on Deforestation and PIPPIB",
            "Analisis Hukum Permen Lingkungan Hidup dan Kehutanan No. P.10\/2019_Madani_2019",
            "Analisis Pelaksanaan Deklarasi Manokwari dalam Rancangan Peraturan Daerah Khusus Provinsi Papua Barat Tentang Pembangunan Berkelanjutan di Papua Barat_Madani_2019",
            "Analisis Substansi Inpres Moratorium Sawit No. 8 2018",
            "Masukan CSO untuk Dokumen Updated NDC",
            "Masukan RPP UU CK Bidang Kehutanan",
            "(RFN Updates Policy Development Jan-Mar 2019) NDC developments in the forestry sector - Indonesia"
        ];

        $filesources = [
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani",
            "Madani"
        ];

        $years = [
            2020,
            2021,
            2021,
            2020,
            2020,
            2020,
            2020,
            2020,
            2020,
            2020,
            2020,
            2020,
            2020,
            2020,
            2021,
            2020,
            2021,
            2020,
            2020,
            2021,
            2020,
            2020,
            2020,
            2020,
            2020,
            2020,
            2020,
            2019,
            2020,
            2019,
            2020,
            2020,
            2019,
            2019,
            2018,
            2020,
            2020,
            2019
        ];
        $links = [
            "https://drive.google.com/file/d/1Pdr2lVFKICrB6vSAUS-SEHzeRrw4cYqf/view?usp=sharing",
            "https://drive.google.com/file/d/1AEs9xbPYgCj-snK1cLQTuvJi9vckBKuU/view?usp=sharing",
            "https://drive.google.com/file/d/1FWAbv38tfWWnGBviAQ2528ATXpumazPM/view?usp=sharing",
            "https://drive.google.com/file/d/1pQ6qb6jr-huy7273czhLb2HmzGU2R1ky/view?usp=sharing",
            "https://drive.google.com/file/d/1KIwwuR9iTIRXrZW9KL97HWj8-bWpy-qn/view?usp=sharing",
            "https://drive.google.com/file/d/10Fh3zoiGpUW-Ar-CmSV8LmBhgTca67ae/view?usp=sharing",
            "https://drive.google.com/file/d/1AcupDDGnMxbvKmMzStj6qKXJHJ6_JKCx/view?usp=sharing",
            "https://drive.google.com/file/d/1kLWOLO_NsXgNz1PG2xwUXvX-ujqDlM6b/view?usp=sharing",
            "https://drive.google.com/file/d/1HIoMFNYX2R7ky-QV-cea5fLsd4v6gQ5T/view?usp=sharing",
            "https://drive.google.com/file/d/1-j1duFsT5YJntFUP25Z-bkWs7YYMWNjA/view?usp=sharing",
            "https://drive.google.com/file/d/1GJSY7jEPJfP3xsgJjTlhELmNeqyYeaLL/view?usp=sharing",
            "https://drive.google.com/file/d/1omn1SwtqGDzpBNNxkzX7JSDE5q_1NOPb/view?usp=sharing",
            "https://drive.google.com/file/d/172nGnzBmXFQDEa3p5ti-g-qd4ZKPd8si/view?usp=sharing",
            "https://drive.google.com/file/d/1rcpk-UEWSpHRLZvCSe-dPrvzmUekebg7/view?usp=sharing",
            "https://drive.google.com/file/d/161T5v-hcLwNJZQksd7WVBK_SNI7Ic17N/view?usp=sharing",
            "https://drive.google.com/file/d/1_Crqlw4dbiGB_G-OlGiYRojS8cxSMeeU/view?usp=sharing",
            "https://drive.google.com/file/d/1rT5SzTtdVBux4o0ZfPLJSSvn9hEjqV55/view?usp=sharing",
            "https://drive.google.com/file/d/1jQsN4-zpPCpNkUh4fI8kqbLWM2nm3zkO/view?usp=sharing",
            "https://drive.google.com/file/d/1AUQLbAbpTHMOgCCeDv53fi4haRstT7oF/view?usp=sharing",
            "https://drive.google.com/file/d/1EW-R00gg15xnYERIwZPBUD3MpPT4XeVK/view?usp=sharing",
            "https://drive.google.com/file/d/1s65uC4kfU5QqpBaHPfU2V1IHSCJE04a-/view?usp=sharing",
            "https://drive.google.com/file/d/1rJ9zuhCfBmmitn4UEXcxeVw9Co9VxOd4/view?usp=sharing",
            "https://drive.google.com/file/d/1iTcRPeCJ0muDAAVdk59rAR799S7acfW6/view?usp=sharing",
            "https://drive.google.com/file/d/1jnoWQLfGniBk9PkkQABBJgw9jBwf-36M/view?usp=sharing",
            "https://drive.google.com/file/d/1dzK--X_OBOWQYDSC7MHs3kbwo1aCHKih/view?usp=sharing",
            "https://drive.google.com/file/d/1_KUtEXq8bSiSz8FfcqBWDw2iTYaZlvp9/view?usp=sharing",
            "https://drive.google.com/file/d/1-igsyephDxQDXPqOALSBeWmwP7MV22RX/view?usp=sharing",
            "https://drive.google.com/file/d/1OIBLLwAvmKxn-bZbSX9cQ_jPP7iyELjq/view?usp=sharing",
            "https://drive.google.com/file/d/1gFZ4r3yQpGvu1nl3LEwldiKt_O1bV5HJ/view?usp=sharing",
            "https://drive.google.com/file/d/1NW53urunxVAxAZYlol4qoAkWtrk9hF_4/view?usp=sharing",
            "https://drive.google.com/file/d/1DtxvrJpiPq61W8jHMQoATeEsQzRqWXkF/view?usp=sharing",
            "",
            "https://drive.google.com/file/d/1McF-VN8EXPHmXuDZfirVwOJUZwzdWZP7/view?usp=sharing",
            "https://docs.google.com/document/d/1T3LpL2qur7nhrsmB42khXGTvG_87r2Pd/edit?usp=sharing&amp;ouid=113880295549964566124&amp;rtpof=true&amp;sd=true",
            "https://drive.google.com/file/d/1dlqlQKj-MUNw3rbKCHO6gRhvggBLb7xA/view?usp=sharing",
            "https://drive.google.com/file/d/1TVM8Cu0JH90pVBRmYuJ8AFvzD2Z7LsGk/view?usp=sharing",
            "https://drive.google.com/file/d/1Y4hZUeoLwCoQ084Eu4HdsaGrWE_ArZfc/view?usp=sharing",
            "https://drive.google.com/file/d/1-aZ3Fkthif8_2AJbmu1IJrv0FyCSQ_uM/view?usp=sharing",

        ];
        $desc = [
            "Ruang lingkup, mandat, program, dan kegiatan dalam RAN KSB: 1) Pembentukan Tim RAN KSB, 2) Penguatan data dasar sawit, 3) Peningkatan kapasitas dan kapabilitas pekebun, 4) Pengelolaan dan pemantauan lingkungan, 5) Pembangunan infrastruktur, 6) Pemanfaatan sawit sebagai energi terbarukan, 7) Penyelesaian status perkebunan lahan sawit dan konflik agraria, 8) Peningkatan kepatuhan hukum, 9) Diplomasi internasional\nCatatan dan rekomendasi untuk RAN KSB 2019-2024",
            "Analisis Peraturan Menteri Pertanian No. 38 Tahun 2020 tentang Penyelenggaraan Sertifikasi Perkebunan Berkelanjutan Indonesia\nTata cara permohonan sertifikasi ISPO\nPrinsip dan Kriteria Permentan 38\/2020 dibandingkan dengan Permentan 11\/2015",
            "What's new in Permentan 38\/2020 on Indonesian Sustainable Palm Oil (environmental management, customary rights, transparency)",
            "Kondisi Gambut Indonesia Terkini\nTelisik Ekosistem Gambut di Area Izin dan Konsesi\nTelisik Ekosistem Gambut di PIPPIB, PIAPS, dan Wilayah Adat\nTarget Restorasi BRGM dan Komitmen Iklim Indonesia\nBRGM dan Pembelajaran Restorasi Gambut 2016-2020",
            "Review of 2019 fires: 1) land cover, 2) peat ecosystem, 3) newly-burned areas, 4) most affected provinces, 5) fires in protected areas, PIPPIB, PIAPS, 6) fires in palm oil and other permits, 7) Fire-Prone Areas",
            "Sorotan RPJMN 2020-2024 terkait: 1) Hutan alam dan kawasan lindung, 2) hutan di lahan gambut, 3) restorasi gambut, 4) rehabilitasi hutan dan lahan, 5) karhutla, 6) tingkat dan intensitas emisi, 7) major projects dan proyek strategis nasional, 8) pembangunan di Papua, 9) perhutanan sosial dan reforma agraria, 10) masyarakat adat ",
            "MA Perintahkan Jokowi Cabut Aturan Hutan Lindung Bisa Jadi Perkebunan.Bentuk Pemerintahan Untuk Ibu Kota Baru\nOmnibus Law dan Perlindungan Lingkungan Hidup\nPenangkapan Editor Mongabay.com.",
            "Sawit dan Kemiskinan Masyarakat Kalimantan Barat\nLuas dan Produktivitas Sawit Kalimantan Barat\nRekomendasi Desa Peduli Api Bagi Kalimantan Barat",
            "Perusahaan Sawit dan Kemandirian Desa di Kalbar (Antara Data & Fakta)\nKontribusi Perusahaan Sawit Pada Pembangunan Desa di Kalbar\nPenyebab Rendahnya Nilai Indeks Desa Membangun yang Bersinggungan dengan Lokasi HGU",
            "Perkembangan RUU Cipta Kerja\nRUU Minerba Disahkan\nWHO Bicara Sawit\nPermendag No. 15 Tahun 2020 yang Menghapus Kewajiban V-Legal\nDicabut, Permen PHPL dan SLK akan Direvisi\\",
            "Pemerintah Terbitkan Perpres tentang ISPO\nMenteri Perdagangan Terbitkan Permendag tentang Ketentuan Ekspor\nProduk Industri Kehutanan\nStrategi Penanganan Ekonomi Menghadapi Dampak Covid-19\nPembahasan RUU Cipta Kerja dan RUU Masyarakat Adat di Tengah\nPandemi Covid",
            "Pemutusan Kerja Sama Kementerian Lingkungan Hidup dan Kehutanan\ndengan WWF Indonesia\nIsu Keamanan Pangan dari Sawit Indonesia\nPerkembangan Omnibus Law RUU Cipta Kerja",
            "Regulation that Undermined Timber Legality Verification System (SVLK) Revoked\nOmnibus Law\/Job Creation Bill Discussion Continues\nMineral and Coal Revision Bill Signed into Law",
            "REDD+ Results-Based Payment: Norway and Green Climate Fund\nGovernment Regulation on Forest Rehabilitation and Reclamation (PP 26\/2020)\nEconomy Recovery Plan (incl. Biodiesel Subsidy)\nFood Estate on Peatland and Other National Strategic Projects\nDraft Presidential Regulation on Carbon Pricing to Attain NDC",
            "Penggunaan Dana, Rincian Program, Pengelolaan Proyek\nSafeguards, Masyarakat Adat, FPIC, Hutan Alam\nTransparansi, Partisipasi dan Gender, Mekanisme Keluhan\nFREL, Catatan Panel Penasihat Teknis Independen\nTantangan Implementasi dan Kegiatan Prioritas untuk Didanai (Matriks Masukan Masyarakat Sipil)",
            "Kondisi yang Diharapkan pada RKP 2021\nFokus Kebijakan pada RKP 2021\nArah Strategi Pendanaan Pembangunan pada RKP\n2021\nAgenda Lingkungan Hidup dan Masyarakat Adat",
            "Food Estate sebagai Solusi Masalah Pangan\nIndonesia?\nKarpet Merah Kebijakan untuk Food Estate\nHutan Alam dan Lahan Gambut di Area of Interest Food Estate (Papua, Kalteng, Sumut,Sumsel)\nPotensi Nilai Kayu dari Hutan Alam dalam AOI Food Estate\nFood Estate dan Safeguards Tersisa\nIndeks Ketahanan Pangan 34 Provinsi",
            "Hutan dan gambut di Provinsi dan Kabupaten peserta Pilkada Serentak 2020\nRusaknya hutan dan bencana\nKewenangan pemerintah daerah dalam menentukan nasib hutan dan gambut",
            "Forest definitions, deforestation, calculation methodologies, natural forest loss, tree cover loss, FREL",
            "Klaster Perlindungan Dan Pengelolaan Lingkungan Hidup\nKlaster Pengelolaan Tata Ruang\nKlaster Kehutanan dan Gambut\nKlaster Perkebunan",
            "Komite Penanganan Covid-19 dan Pemulihan Ekonomi Nasional (Perpres\n82\/2020)\nNasib Badan Restorasi Gambut\nKelanjutan Kerja Sama Indonesia-Norwegia terkait REDD+\nRencana Peraturan Nilai Ekonomi Karbon\nLaporan Koalisi Masyarakat Adat kepada Komite PBB untuk Penghapusan\nDiskriminasi Rasial\nAncaman terhadap Hutan Harapan di Jambi dan Sumatra Selatan",
            "Perubahan pengaturan terkait Hutan Tanaman Rakyat",
            "Penguatan dan Pelemahan Kewenangan KLHK\ndi Perpres 92\/2020",
            "Perkembangan RUU Cipta Kerja \nRUU Minerba Disahkan\nWHO Bicara Sawit \nPermendag No. 15 Tahun 2020 yang Menghapus Kewajiban V-Legal Dicabut, Permen PHPL dan SLK akan Direvisi",
            "Isu Keamanan Pangan dari Sawit Indonesia\nPerkembangan Omnibus Law RUU Cipta Kerja\nPerkembangan Pembahasan Revisi UU Minerba",
            "Dana Insentif REDD+ Norwegia\nPembangunan Rendah Karbon di Fase New Normal \nPresiden Teken PP perihal Rehabilitasi dan Reklamasi Hutan\nSkema Pemulihan Ekonomi NasionalPemerintah Mengusulkan 89 Proyek Strategis Nasional",
            "Highlights of Presidential Regulation No. 44\/2020 2\nISPO Certification System: Now and then\nCivil society concerns\nISPO vs RSPO",
            "The Emissions Reduction Report\nSafeguards",
            "Risks of Omnibus Bill to natural forests",
            "Potential of social forestry for NDC\nCalculating Contributions of Social Forestry to NDC:\nCase Study of Bukit Barisan Forest Management Unit in West \nSumatra\nCommunity REDD+ Project in Bujang Raba\nLandscape",
            "Risiko UU Cipta Kerja terhadap hutan alam dan DAS",
            "Indonesia’s Deforestation Rate 2019\nIndicative Map of Permanent Forest Moratorium (PIPPIB) 2020\nForest Fire 2019 \nSocial Forestry Realization May 2019\nUpdated Nationally Determined Contribution (NDC) 2020 ",
            "",
            "",
            "",
            "",
            "",
            ""
        ];



        foreach ($categories as $i => $val) {
            DB::table('publications')->insert([
                [
                    "category" => $categories[$i],
                    "tags" => $tags[$i],
                    "file_name" => $filenames[$i],
                    "file_source" => $filesources[$i],
                    "year" => $years[$i],
                    "folder" => $links[$i],
                    "doc_description" => $desc[$i],
                    "created_at" => now(),
                    "updated_at" => now()
                ],
            ]);
        }
    }
}
