<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TabularDataSeeder extends Seeder
{

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $categories = [
            "Karhutla",
            "Sawit",
            "Biofuel",
            "Biofuel",
            "Biofuel",
            "Sawit",
            "Hutan Alam",
            "Hutan Alam",
            "Biofuel",
            "Konsesi",
            "Karhutla",
            "Karhutla",
            "Sawit",
            "Sawit",
            "Perhutanan Sosial",
            "Sawit",
            "Sawit",
            "Hutan Alam",
            "Gambut",
            "Karhutla",
            "Sawit",
            "Hutan Alam",
            "Hutan Alam",
            "Hutan Alam",
            "Hutan Alam",
            "Hutan Alam",
            "Hutan Alam, Sawit",
            "Karhutla",
            "Sawit",
            "Sawit",
            "Deforestasi",
            "Sawit",
            "Pilpres",
            "Karhutla",
            "Gambut",
            "Deforestasi",
            "Perhutanan Sosial",
            "Perhutanan Sosial",
            "Deforestasi",
            "Deforestasi",
            "Karhutla",
            "Hutan Alam",
            "Bencana",
            "Bencana",
            "Sawit",
            "Deforestasi",
            "Deforestasi",
            "Deforestasi",
            "Hutan Alam",
            "Hutan alam",
            "Sawit",
            "Hutan Alam, Gambut",
            "Sawit",
            "Sawit",
            "Sawit",
            "Sawit",
            "Deforestasi",
            "Karhutla",
            "Pilkada",
            "Deforestasi",
            "Karhutla",
            "Konsesi",
            "Masyarakat Adat",
            "Gambut",
            "Konsesi",
            "Sawit",
            "Sawit",
            "Deforestasi",
            "Hutan Alam",
            "Hutan Alam",
            "Hutan Alam",
            "Sawit",
            "Hutan Alam",
            "Hutan Alam",
            "Karhutla",
            "Hutan Alam",
            "Hutan Alam",
            "Sawit",
            "Konsesi"
           ];

        $filenames = [
            "Area Baru Terbakar ABT Kalteng, Sumsel, Kalbar_Madani_2020_Excel",
            "Analisis Data Konsesi Sawit GP dan Auriga_Madani_2019_Excel",
            "Analisis Omnimbus Law - Annex XX Neraca Biodiesel dan CPO Skenario B30D10 Analysis_Madani_2020_Word",
            "Analisis Omnimbus Law - Biofuel Worksheet_Madani_2020_Excel",
            "Analisis Omnimbus Law - Ekspor Impor CPO dan PKO Nasional 2000 - 2018 (BPS)_Madani_2020_Excel",
            "Analisis Omnimbus Law - Luas dan Produktivitas Lahan 1970 - 2018_Madani_2020_Excel",
            "Analisis Omnimbus Law - Data Tabular Mas Fadli_Madani_2020_Excel",
            "Analisis Pilkada_Madani_2020_Excel",
            "Biofuel Worksheet_Madani_2020_Excel",
            "Concession Risk Ranking_Greenpeace_2016",
            "Area Terbakar 2019 dalam Izin Sawit di Gambut + Kawasan Hutan_Madani_2020_Excel",
            "Area Terbakar 2019 dalam Izin Sawit di Gambut + Tutupan Lahan_Madani_2020_Excel",
            "Daftar Kabupaten dengan Tutupan Hutan Terluas dalam Konsesi_Greenpeace_2019_Excel.",
            "Daftar Konsesi Sawit_Greenpeace_2019_Excel",
            "Daftar Lokasi ProKlim dalam SRN 2018 - Wilayah Sumatera_Madani_2018_Excel",
            "Tutupan Sawit (Kota-Kab)_WRI_2020_Excel",
            "Tutupan Sawit di Gambut (Kota-Kab)_WRI_2020_Excel",
            "Luasan Hutan Alam di APL tiap Kabupaten Kota_Madani_2020_Excel",
            "Luasan Gambut di Tiap Kabupaten Kota_Madani_2020_Excel",
            "Luasan Area Terbakar di Tiap Kabupaten Kota _Madani_2020_Excel",
            "Luasan Izin Sawit dan Pohon Sawit di Tiap Kabupaten Kota_Madani_2020_Excel",
            "HA dalam Konsesi Pilkada_Madani_2020_Excel",
            "Luasan Hutan Alam berdasarkan Tutupan Lahan per Kabupaten 2018_Madani_2020_Excel",
            "HA 19 R05_Madani_2020_Excel",
            "Luas Hutan Alam 2019_Madani_2020_Excel",
            "Hutan Alam 2019_Madani_2020_Excel",
            "Hutan Alam di Izin Sawit_Madani_2020_Excel",
            "Hutan yang Terbakar_Madani_2020_Excel",
            "Izin Sawit dan Tutupan Sawit_Madani_2020_Excel",
            "NTPR X Luas Smallholder 10 Provinsi Smallholder Terluas_Madani_2020_Excel",
            "Komen Defor Indonesia 2019-2020_MADANI_2021_EXCEL",
            "Laju Luas Lahan Sawit per Sektor_Madani_2020_Excel",
            "LHKPN - Penghitungan LHKPN Capres 2019_Madani_2018_Excel",
            "Resume Statistik Covid Karhutla_Madani_2020_Excel",
            "Statistik AT19 IS TL FEG Prov_Madani_2020_Excel",
            "LTS Deforestation Scenario_MADANI_2021_EXCEL",
            "Capaian Perhutanan Sosial sd 1 April 2019_Dirjen PSKL_2019_PDF",
            "Capaian Perhutanan Sosial sd 02.05.20_2020_JPG",
            "Data Deforestasi 23 April 2018_KLHK_2018_Excel",
            "Data Deforestasi 26 April 2018_KLHK_2018_Excel",
            "Data Jejak Terbakar_Madani_2020_Excel",
            "Data Kehutanan Provinsi Papua Barat_Madani_2018_Excel",
            "Data Kerugian Bencana - Intensitas Bencana_BNPB_2018_Excel",
            "Data Kerugian Bencana - Ringkasan APBD 2017_Eko Nur Subagyo_2018_Excel",
            "Data Statistik Izin Sawit dan Tertanam Sawit_Madani_2020_Excel",
            "Deforestasi Bruto_Madani_2020_Excel",
            "Deforestasi di Wilayah IzinKonsesi Kumulatif 2003 - 2018_Madani_2020_Excel",
            "Deforestasi_Madani_2020_Excel",
            "Fakta Hutan Papua_Madani_2018_Excel",
            "HA di HP dan HPT_Madani_2020_Excel",
            "Harga TBS 2013 - 2018 Dirjenbun_Madani_2020_Excel",
            "Hutan Alam dan Gambut di Izin Sawit di PIPPIB_Madani_2020_Excel",
            "Konsesi Sawit di Gambut_Madani_2019_Excel",
            "Laju Luas Lahan Sawit per Sektor_Madani_2020_Excel",
            "Luas Lahan Sawit Tidak Menghasilkan Smallholder_Madani_2020_Excel",
            "Masterdata Sawit_Madani_2019_Excel",
            "Rekap Deforestasi 2013-2014_Madani_2018_Excel",
            "Rekapitulasi Luas Kebakaran Hutan dan Lahan per Provinsi di Indonesia 2013 - 2018_Dirjen PKHL_2018_PDF",
            "Resume Data Pilkada_Madani_2020_Excel",
            "Resume Matriks Perbandingan Deforestasi Madani GFW FWI_Madani_2020_Excel",
            "Resume Statistik Covid Karhutla_Madani_2020_Excel",
            "Resume Tumpang Tindih_Madani_2020_Excel",
            "Sikap Anggota DPR Terhadap RUU Masyarakat Adat_Madani_2018_Excel",
            "Statistik AT19 IS TL FEG Prov_Madani_2020_Excel",
            "Statistik Jumlah HPH 2001-2016 BPS_BPS_2018_Excel",
            "Statistik Sawit Nasional 2010 - 2019__Madani_2020_Excel",
            "Tabel Analisis Masalah Workshop Moratorium Sawit CLUA_Madani_2019_Excel",
            "Tabel Deforestasi_Madani_2018_Word",
            "Tabel FREL Subnasional Interprestasi_Madani_2019_Word",
            "Tabel FREL Subnasional Pak Ridwan_Madani_2019_Excel",
            "Tabel Hutan Alam Berisiko Terancam dan Sangat Terancam 2020_Madani_2020_Word",
            "Tabular Izin dan Area Tertanam Sawit_Madani_2020_Excel",
            "Tabulasi Hutan Alam Primer Sekunder Kabkot dan Fungsi Kawasan Hutan_Madani_2020_Excel",
            "TABULASI HUTAN ALAM PRIMER SEKUNDER KABKOT dan FUNGSI KAWASAN HUTAN_TUF_2021_EXCEL",
            "Total Areal APL _ Sawit Provinsi_Auriga_2019_Excel",
            "Track Visi Misi Prabowo_Madani_2018_Excel",
            "Tracking Visi dan Misi Capres terkait Lingkungan_Madani_2018_Excel",
            "Tutupan Sawit dalam Kawasan Hutan_KPK_2019_png",
            "List of PO Companies in PIPPIB 2020_Madani_2020_Excel"
           ];

        $doc_description = [
            "Luas Area Baru Terbakar ABT Kalteng, Sumsel, Kalbar",
            "Data Tabular Sawit Greenpeace dan Auriga ",
            "Annex XX Neraca Biodiesel dan CPO Skenario B30D10 Analysis",
            "Biofuel worksheet",
            "Ekspor Impor CPO dan PKO Nasional 2000 - 2018 (BPS)",
            "Luas dan produktivitas lahan 1970 - 2018",
            "Luas administrasi dan luas hutan setiap provinsi",
            "Hutan Alam di Provinsi dan Kabupaten Pilkada 2020",
            "• Political-economic background\n• Impacts on forests and land\n• Index Mundi\n• Collective auction\n• Current work on biofuel",
            "Company Name, Problematic Area, Forest Cover, Ranking",
            "Area Terbakar 2019 dalam Izin Sawit di Gambut + Kawasan Hutan",
            "Area Terbakar 2019 dalam Izin Sawit di Gambut + Tutupan Lahan",
            "Luasan Izin Sawit dan Pohon Sawit di Area Gambut di Tiap Kabupaten Kota",
            "Nama Perusahaan, Luas Konsesi, Luas Hutan Alam, Luas Gambut",
            "Nama Kegiatan, Kab\/Kota, Provinsi, Status, No Akun",
            "Luas tutupan sawit Provinsi - Kota\/ Kabupaten",
            "Luas tutupan sawit di Gambut Provinsi - Kota\/ Kabupaten",
            "Luasan Hutan Alam di APL tiap Kabupaten Kota",
            "Luasan Gambut di Tiap Kabupaten Kota",
            "Luasan Area Terbakar di Tiap Kabupaten Kota",
            "Luasan Izin Sawit dan Pohon Sawit di Tiap Kabupaten Kota",
            "Hutan Alam di Provinsi dan Kabupaten Pilkada 2020",
            "Luasan Hutan Alam berdasarkan Tutupan Lahan per Kabupaten 2018",
            "Hutan Alam tahun 2019",
            "Luas hutan alam 2019 (7sheet)",
            "Luas hutan alam 2019 (1sheet)",
            "• Data izin sawit CSO\n• Data izin sawit RSPO\n• Data pelepasan kawasan hutan",
            "Luasan hutan yang terbakar",
            "Izin Sawit dan Tutupan Sawit",
            "NTPR X Luas Smallholder 10 Provinsi Smallholder Terluas",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
           ];

        foreach ($categories as $i => $val) {
            DB::table('tabular_data')->insert([
                [
                    "category" => $categories[$i],
                    "tags" => "",
                    "file_name" => $filenames[$i],
                    "doc_description" => $doc_description[$i],
                    "created_at" => now(),
                    "updated_at" => now()
                ],
            ]);
        }
    }
}
